    <footer id="footer">
        <nav>
            <h1>Navigation</h1>
            <ul>
				<li><a href="/features/">Features</a></li>
                <li><a href="/documentation/">Documentation</a></li>
                <li><a href="/download/">Download</a></li>
                <li><a href="/blog/">Blog</a></li>
            </ul>
        </nav>
        <nav>
            <h1>Keep in Touch!</h1>
          <ul>
            <li>
              <a href="http://twitter.com/brightstardb" class="twitter-follow-button" data-show-count="false">
                Follow @BrightstarDB
              </a>
              <script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
            </li>
            <li>
              <div data-href="http://brightstardb.com/" class="g-plusone" data-size="medium" style="display:inline-block"></div>
            </li>
            <li>
              <a href="/blog/?feed=rss2">
                <img src="/images/feed-icon16x16.png" alt="RSS Feed Icon" style="vertical-align: middle" border="0" />&nbsp;Blog RSS Feed
              </a>
            </li>
          </ul>
        </nav>
      <nav>
        <h1>Legal</h1>
        <ul>
          <li>
            <a href="/cookiepolicy.html">Cookie Policy</a>
          </li>
          <li>
            <a href="/privacypolicy.html">Privacy Policy</a>
          </li>
        </ul>
      </nav>
    </footer>

    <!-- Place this tag in your head or just before your close body tag -->
    <script type="text/javascript" src="https://apis.google.com/js/plusone.js">
        { lang: 'en-GB' }
    </script>
    <!-- google analytics -->
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-25503555-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>