<header id="header">
        <hgroup>
		<a href="/">
            <img class="logo" src="/images/logo.png" alt="BrightstarDB" width="366" height="66" />
		</a>
            <form method="get" action="/search.html" id="searchForm">
            <input id="q" type="text" name="q" />
            <button title="Search" class="button">
                <img src="/images/mag.png" alt="Search" class="mag" />
            </button>
            </form>
        </hgroup>
    </header>
    <nav id="sitenav">
		<a href="/features/">Features</a>
      <a href="/documentation/">Docs</a>
        <a href="/download/">Download</a>
        <a href="/blog/">Blog</a> 
    </nav>
