image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y
  
before_build:
    - dotnet --version
    - dotnet restore src/core/core.sln

build_script:
    - gitversion /l console /output buildserver /updateassemblyinfo
    - dotnet build -c Release src/core/core.sln

test:
    - src/core/BrightstarDB.InternalTests/bin/Release/net451/BrightstarDB.InternalTests.dll
    - src/core/BrightstarDB.InternalTests/bin/Release/netcoreapp1.0/BrightstarDB.InternalTests.dll
    - src/core/BrightstarDB.InternalTests/bin/Release/netcoreapp2.0/BrightstarDB.InternalTests.dll

