image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y
  
before_build:
    - dotnet --version
    - dotnet restore src/core/core.sln

build_script: |
  gitversion /l console /output buildserver /updateassemblyinfo
  dotnet build -c Release src/core/core.sln
  dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets -p:PackageVersion=%GitVersion_NugetVersion% src\core\BrightstarDB 
  dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets -p:PackageVersion=%GitVersion_NugetVersion% src\core\BrightstarDB.CodeGeneration
  dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets -p:PackageVersion=%GitVersion_NugetVersion% src\core\BrightstarDB.CodeGeneration.Console
  dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets src\core\BrightstarDB\BrightstarDB.csproj -p:NuspecFile=..\..\..\installer\nuget\BrightstarDB.nuspec -p:NuspecBasePath=. -p:NuspecProperties="version=%GitVersion_NugetVersion%" --no-build

before_test:
    - ps: |
        pushd .\src\core\BrightstarDB.InternalTests
        nuget install Appveyor.TestLogger
        popd
        pushd .\src\core\BrightstarDB.CodeGeneration.Tests
        nuget install Appveyor.TestLogger
        popd
        pushd .\src\core\BrightstarDB.EntityFramework.Tests
        nuget install Appveyor.TestLogger
        popd
        pushd .\src\core\BrightstarDB.Tests
        nuget install Appveyor.TestLogger
        popd
        pushd .\src\core\BrightstarDB.Server.Modules.Tests
        nuget install Appveyor.TestLogger
        popd

test_script:
    - dotnet test -c Release --test-adapter-path:. --logger:Appveyor src\core\BrightstarDB.InternalTests\BrightstarDB.InternalTests.csproj
    - dotnet test -c Release --test-adapter-path:. --logger:Appveyor src\core\BrightstarDB.Tests\BrightstarDB.Tests.csproj
    - dotnet test -c Release --test-adapter-path:. --logger:Appveyor src\core\BrightstarDB.Server.Modules.Tests\BrightstarDB.Server.Modules.Tests.csproj
    - dotnet test -c Release --test-adapter-path:. --logger:Appveyor src\core\BrightstarDB.EntityFramework.Tests\BrightstarDB.EntityFramework.Tests.csproj
    - dotnet test -c Release --test-adapter-path:. --logger:Appveyor src\core\BrightstarDB.CodeGeneration.Tests\BrightstarDB.CodeGeneration.Tests.csproj

deploy:
  - provider: GitHub
    description: 'BrightstarDB $(GitVersion_SemVer)'
    auth_token:
      secure: YVdYJs6Uiw69xZTcA1TNVU1YnmbCMXh3MjNRqDno9y8JnzNF5oojc+tJIrj+MaJX
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: rrONi037gQf8j+mGvpP1DPwcKPqg77dvqBYJ7UNvaMcBfNOlBJRUE58TZFjYWS0P
    on:
      appveyor_repo_tag: true
    artifact: /.*\.nupkg/

artifacts:
  - path: 'nugets\*.nupkg'
    