version: 1.0.{build}

environment:
  NoPortable: True

install:
- ps:
  $AndroidToolPath = "${env:ProgramFiles(x86)}\\Android\\android-sdk\\tools\\android"
  $sdkmanager = "${env:ProgramFiles(x86)}\\Android\\android-sdk\\tools\\bin\\sdkmanager"
  Function Get-AndroidSDKs() {
    $output = & $AndroidToolPath list sdk --all
    $sdks = $output |% {
      if ($_ -match '(?<index>\\d+)- (?<sdk>.+), revision (?<revision>[\\d\\.]+)') {
        $sdk = New-Object PSObject
        Add-Member -InputObject $sdk -MemberType NoteProperty -Name Index -Value $Matches.index
        Add-Member -InputObject $sdk -MemberType NoteProperty -Name Name -Value $Matches.sdk
        Add-Member -InputObject $sdk -MemberType NoteProperty -Name Revision -Value $Matches.revision
        $sdk
      }
    }
    $sdks 
  }
  Function Install-AndroidSDK() {
    [CmdletBinding()]
    Param(
      [Parameter(Mandatory=$true, Position=0)]
      [PSObject[]]$sdks
    )
    $sdkIndexes = $sdks |% { $_.Index }
    foreach($sdkIndexArgument in $sdkIndexes) {
      "y" | & $AndroidToolPath update sdk -u -a -t $sdkIndexArgument
    }
  }
  $sdks = Get-AndroidSDKs |? { $_.name -like 'sdk platform*API 10*' -or $_.name -like 'google apis*api 10' }
  echo $sdks\nInstall-AndroidSDK -sdks $sdks
  
build_script:
- cmd: msbuild build.proj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Build;BuildTests