image: Visual Studio 2017
version: 1.0.{build}

environment:
  NoPortable: True

install:
  
build_script:
    - dotnet build -c $(CONFIGURATION) src/core/core.sln

test_script:
    - dotnet test -C $(CONFIGURATION) src/core/BrightstarDB.InternalTests
    - dotnet test -C $(CONFIGURATION) src/core/BrightstarDB.CodeGeneration.Tests
    - dotnet test -C $(CONFIGURATION) src/core/BrightstarDB.EntityFramework.Tests
    - dotnet test -C $(CONFIGURATION) src/core/BrightstarDB.Tests
