image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y
  
before_build:
    - dotnet --version
    - dotnet restore src/core/core.sln

build_script:
    - gitversion /l console /output buildserver /updateassemblyinfo
    - dotnet build -c Release src/core/core.sln

before_test:
    - ps: |
        cd src\core\BrightstarDB
        nuget install Appveyor.TestLogger

test_script:
    - dotnet test -c Release --test-adapter-path:. --logger:Appveyor src/core/BrightstarDB.InternalTests 

#on_finish:
#    - ps: |
#        $wc = New-Object 'System.Net.WebClient'
#        $filenames = Get-ChildItem -Path ".\src\core" -Recurse -Include *.trx
#        foreach ($f in $filenames) {
#            $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", $f.FullName)
#        } 