image: Visual Studio 2017
version: 1.0.{build}

environment:
  NoPortable: True
  
install:
  - choco install gitversion.portable -pre -y
  
before_build:
    - dotnet restore src/core/core.sln

build_script:
    - gitversion /l console /output buildserver /updateassemblyinfo
    - dotnet build -c Release src/core/core.sln

test:
    assemblies:
        only:
            - BrightstarDB.InternalTests.dll
