image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y
  
before_build:
    - dotnet --version
    - dotnet restore src/core/core.sln

build_script:
    - gitversion /l console /output buildserver /updateassemblyinfo
    - dotnet build -c Release src/core/core.sln

before_test:
    - ps: |
        pushd .\src\core\BrightstarDB.InternalTests
        nuget install Appveyor.TestLogger
        popd
        pushd .\src\core\BrightstarDB.CodeGeneration.Tests
        nuget install Appveyor.TestLogger
        popd
        pushd .\src\core\BrightstarDB.EntityFramework.Tests
        nuget install Appveyor.TestLogger
        popd
        pushd .\src\core\BrightstarDB.Tests
        nuget install Appveyor.TestLogger
        popd

test_script:
    - dotnet test -c Release --test-adapter-path:. --logger:Appveyor src\core\BrightstarDB.InternalTests\BrightstarDB.InternalTests.csproj
    - dotnet test -c Release --test-adapter-path:. --logger:Appveyor src\core\BrightstarDB.CodeGeneration.Tests\BrightstarDB.CodeGeneration.Tests.csproj
    - dotnet test -c Release --test-adapter-path:. --logger:Appveyor src\core\BrightstarDB.EntityFramework.Tests\BrightstarDB.EntityFramework.Tests.csproj
    - dotnet test -c Release --test-adapter-path:. --logger:Appveyor src\core\BrightstarDB.Tests\BrightstarDB.Tests.csproj
