image: Visual Studio 2017
version: 1.0.{build}

environment:
  NoPortable: True

install:
  - choco install gitversion.portable -pre -y
  
before_build:
    - dotnet restore src/core/core.sln

build_script:
    - gitversion /l console /output buildserver /updateassemblyinfo
    - dotnet build -c $(CONFIGURATION) src/core/core.sln

test_script:
    - dotnet test -C $(CONFIGURATION) src/core/BrightstarDB.InternalTests
    - dotnet test -C $(CONFIGURATION) src/core/BrightstarDB.CodeGeneration.Tests
    - dotnet test -C $(CONFIGURATION) src/core/BrightstarDB.EntityFramework.Tests
    - dotnet test -C $(CONFIGURATION) src/core/BrightstarDB.Tests
