// -----------------------------------------------------------------------
// <autogenerated>
//    This code was generated from a template.
// 
//    Changes to this file may cause incorrect behaviour and will be lost
//    if the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------
namespace ChangeTrackingCore
{
    [System.CodeDom.Compiler.GeneratedCode("BrightstarDB.CodeGeneration", "0.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class EntityContext : global::BrightstarDB.EntityFramework.BrightstarEntityContext
    {
        static EntityContext()
        {
            var provider = new global::BrightstarDB.EntityFramework.ReflectionMappingProvider();
            provider.AddMappingsForType(global::BrightstarDB.EntityFramework.EntityMappingStore.Instance, typeof(global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.IArticle));
            global::BrightstarDB.EntityFramework.EntityMappingStore.Instance.SetImplMapping<global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.IArticle, BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.Article>();
            provider.AddMappingsForType(global::BrightstarDB.EntityFramework.EntityMappingStore.Instance, typeof(global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.ITrackable));
            global::BrightstarDB.EntityFramework.EntityMappingStore.Instance.SetImplMapping<global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.ITrackable, BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.Trackable>();
        }

        public EntityContext()
        {
            this.InitializeContext();
        }

        public EntityContext(global::BrightstarDB.Client.IDataObjectStore dataObjectStore) : base(dataObjectStore)
        {
            this.InitializeContext();
        }

        public EntityContext(string updateGraphUri, global::System.Collections.Generic.IEnumerable<global::System.String> datasetGraphUris, string versionGraphUri) : base(updateGraphUri, datasetGraphUris, versionGraphUri)
        {
            this.InitializeContext();
        }

        public EntityContext(string connectionString, global::System.Boolean? enableOptimisticLocking = null, string updateGraphUri = null, global::System.Collections.Generic.IEnumerable<global::System.String> datasetGraphUris = null, string versionGraphUri = null) : base(connectionString, enableOptimisticLocking, updateGraphUri, datasetGraphUris, versionGraphUri)
        {
            this.InitializeContext();
        }

        private void InitializeContext()
        {
            this._Articles = (new global::BrightstarDB.EntityFramework.BrightstarEntitySet<global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.IArticle>(this));
            this._Trackables = (new global::BrightstarDB.EntityFramework.BrightstarEntitySet<global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.ITrackable>(this));
        }

        public global::BrightstarDB.EntityFramework.IEntitySet<T> EntitySet<T>()
            where T : class
        {
            global::System.Type type = typeof(T);
            if (type.Equals(typeof(global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.IArticle)))
            {
                return (global::BrightstarDB.EntityFramework.IEntitySet<T>)(this.Articles);
            }

            if (type.Equals(typeof(global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.ITrackable)))
            {
                return (global::BrightstarDB.EntityFramework.IEntitySet<T>)(this.Trackables);
            }

            throw new global::System.InvalidOperationException(((typeof(T)).FullName) + (" is not a recognized entity interface type."));
        }

        private global::BrightstarDB.EntityFramework.IEntitySet<global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.IArticle> _Articles;
        internal global::BrightstarDB.EntityFramework.IEntitySet<global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.IArticle> Articles
        {
            get
            {
                return this._Articles;
            }
        }

        private global::BrightstarDB.EntityFramework.IEntitySet<global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.ITrackable> _Trackables;
        internal global::BrightstarDB.EntityFramework.IEntitySet<global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.ITrackable> Trackables
        {
            get
            {
                return this._Trackables;
            }
        }
    }
}
namespace BrightstarDB.Samples.EntityFramework.ChangeTrackingCore
{
    [System.CodeDom.Compiler.GeneratedCode("BrightstarDB.CodeGeneration", "0.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal partial class Article : global::BrightstarDB.EntityFramework.BrightstarEntityObject, global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.IArticle
    {
        public Article()
        {
        }

        public Article(global::BrightstarDB.EntityFramework.BrightstarEntityContext context) : base(context, typeof(Article))
        {
        }

        public Article(global::BrightstarDB.EntityFramework.BrightstarEntityContext context, global::BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject)
        {
        }

        public global::System.String Id
        {
            get
            {
                return base.GetKey();
            }

            set
            {
                base.SetKey(value);
            }
        }

        public global::System.String Title
        {
            get
            {
                return base.GetRelatedProperty<global::System.String>("Title");
            }

            set
            {
                base.SetRelatedProperty("Title", value);
            }
        }

        public global::System.String BodyText
        {
            get
            {
                return base.GetRelatedProperty<global::System.String>("BodyText");
            }

            set
            {
                base.SetRelatedProperty("BodyText", value);
            }
        }

        public global::System.DateTime Created
        {
            get
            {
                return base.GetRelatedProperty<global::System.DateTime>("Created");
            }

            set
            {
                base.SetRelatedProperty("Created", value);
            }
        }

        public global::System.DateTime LastModified
        {
            get
            {
                return base.GetRelatedProperty<global::System.DateTime>("LastModified");
            }

            set
            {
                base.SetRelatedProperty("LastModified", value);
            }
        }
    }
}
namespace BrightstarDB.Samples.EntityFramework.ChangeTrackingCore
{
    [System.CodeDom.Compiler.GeneratedCode("BrightstarDB.CodeGeneration", "0.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal partial class Trackable : global::BrightstarDB.EntityFramework.BrightstarEntityObject, global::BrightstarDB.Samples.EntityFramework.ChangeTrackingCore.ITrackable
    {
        public Trackable()
        {
        }

        public Trackable(global::BrightstarDB.EntityFramework.BrightstarEntityContext context) : base(context, typeof(Trackable))
        {
        }

        public Trackable(global::BrightstarDB.EntityFramework.BrightstarEntityContext context, global::BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject)
        {
        }

        public global::System.DateTime Created
        {
            get
            {
                return base.GetRelatedProperty<global::System.DateTime>("Created");
            }

            set
            {
                base.SetRelatedProperty("Created", value);
            }
        }

        public global::System.DateTime LastModified
        {
            get
            {
                return base.GetRelatedProperty<global::System.DateTime>("LastModified");
            }

            set
            {
                base.SetRelatedProperty("LastModified", value);
            }
        }
    }
}
