//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("1.6.1.0")]
[assembly: AssemblyFileVersion("1.6.1.0")]
[assembly: AssemblyProduct("BrightstarDB")]
[assembly: AssemblyCopyright("Copyright (c) 2014 Khalil Ahmed, Graham Moore, and other contributors")]
[assembly: AssemblyTrademark("All rights reserved")]
[assembly: AssemblyTitle("BrightstarDB Portable Class Library Store Assembly")]


