 

// -----------------------------------------------------------------------
// <autogenerated>
//    This code was generated from a template.
//
//    Changes to this file may cause incorrect behaviour and will be lost
//    if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using BrightstarDB.Client;
using BrightstarDB.EntityFramework;

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace BrightstarDB.Tests.EntityFramework 
{
    public partial class MyEntityContext : BrightstarEntityContext {
    	private static readonly EntityMappingStore TypeMappings;
    	
    	static MyEntityContext() 
    	{
    		TypeMappings = new EntityMappingStore();
    		var provider = new ReflectionMappingProvider();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IAnimal));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IAnimal, BrightstarDB.Tests.EntityFramework.Animal>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IArticle));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IArticle, BrightstarDB.Tests.EntityFramework.Article>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IBaseEntity));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IBaseEntity, BrightstarDB.Tests.EntityFramework.BaseEntity>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.ICompany));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.ICompany, BrightstarDB.Tests.EntityFramework.Company>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IDBPediaPerson));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IDBPediaPerson, BrightstarDB.Tests.EntityFramework.DBPediaPerson>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IDepartment));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IDepartment, BrightstarDB.Tests.EntityFramework.Department>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IDerivedEntity));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IDerivedEntity, BrightstarDB.Tests.EntityFramework.DerivedEntity>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IEntity));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IEntity, BrightstarDB.Tests.EntityFramework.Entity>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IFoafAgent));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IFoafAgent, BrightstarDB.Tests.EntityFramework.FoafAgent>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IFoafPerson));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IFoafPerson, BrightstarDB.Tests.EntityFramework.FoafPerson>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IIdentityClashTest));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IIdentityClashTest, BrightstarDB.Tests.EntityFramework.IdentityClashTest>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IIdentityClashTestLevel1));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IIdentityClashTestLevel1, BrightstarDB.Tests.EntityFramework.IdentityClashTestLevel1>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IIdentityClashTestLevel2));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IIdentityClashTestLevel2, BrightstarDB.Tests.EntityFramework.IdentityClashTestLevel2>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IJobRole));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IJobRole, BrightstarDB.Tests.EntityFramework.JobRole>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IMarket));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IMarket, BrightstarDB.Tests.EntityFramework.Market>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IPerson));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IPerson, BrightstarDB.Tests.EntityFramework.Person>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.ISession));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.ISession, BrightstarDB.Tests.EntityFramework.Session>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.IEveningSession));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.IEveningSession, BrightstarDB.Tests.EntityFramework.EveningSession>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.ITechnicalEveningSession));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.ITechnicalEveningSession, BrightstarDB.Tests.EntityFramework.TechnicalEveningSession>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.ISkill));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.ISkill, BrightstarDB.Tests.EntityFramework.Skill>();
    		provider.AddMappingsForType(TypeMappings, typeof(BrightstarDB.Tests.EntityFramework.ITrackable));
    		TypeMappings.AddImplMapping<BrightstarDB.Tests.EntityFramework.ITrackable, BrightstarDB.Tests.EntityFramework.Trackable>();
    	}
    	
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar
    	/// Data Object Store connection
    	/// </summary>
    	/// <param name="dataObjectStore">The connection to the Brightstar Data Object Store that will provide the entity objects</param>
    	public MyEntityContext(IDataObjectStore dataObjectStore) : base(TypeMappings, dataObjectStore)
    	{
    		InitializeContext();
    	}
    
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar connection string
    	/// </summary>
    	/// <param name="connectionString">The connection to be used to connect to an existing BrightstarDB store</param>
    	/// <param name="enableOptimisticLocking">OPTIONAL: If set to true optmistic locking will be applied to all entity updates</param>
        /// <param name="updateGraphUri">OPTIONAL: The URI identifier of the graph to be updated with any new triples created by operations on the store. If
        /// not defined, the default graph in the store will be updated.</param>
        /// <param name="datasetGraphUris">OPTIONAL: The URI identifiers of the graphs that will be queried to retrieve entities and their properties.
        /// If not defined, all graphs in the store will be queried.</param>
        /// <param name="versionGraphUri">OPTIONAL: The URI identifier of the graph that contains version number statements for entities. 
        /// If not defined, the <paramref name="updateGraphUri"/> will be used.</param>
    	public MyEntityContext(
    	    string connectionString, 
    		bool? enableOptimisticLocking=null,
    		string updateGraphUri = null,
    		IEnumerable<string> datasetGraphUris = null,
    		string versionGraphUri = null
        ) : base(TypeMappings, connectionString, enableOptimisticLocking, updateGraphUri, datasetGraphUris, versionGraphUri)
    	{
    		InitializeContext();
    	}
    
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar
    	/// connection string retrieved from the configuration.
    	/// </summary>
    	public MyEntityContext() : base(TypeMappings)
    	{
    		InitializeContext();
    	}
    	
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar
    	/// connection string retrieved from the configuration and the
    	//  specified target graphs
    	/// </summary>
        /// <param name="updateGraphUri">The URI identifier of the graph to be updated with any new triples created by operations on the store. If
        /// set to null, the default graph in the store will be updated.</param>
        /// <param name="datasetGraphUris">The URI identifiers of the graphs that will be queried to retrieve entities and their properties.
        /// If set to null, all graphs in the store will be queried.</param>
        /// <param name="versionGraphUri">The URI identifier of the graph that contains version number statements for entities. 
        /// If set to null, the value of <paramref name="updateGraphUri"/> will be used.</param>
    	public MyEntityContext(
    		string updateGraphUri,
    		IEnumerable<string> datasetGraphUris,
    		string versionGraphUri
    	) : base(TypeMappings, updateGraphUri:updateGraphUri, datasetGraphUris:datasetGraphUris, versionGraphUri:versionGraphUri)
    	{
    		InitializeContext();
    	}
    	
    	private void InitializeContext() 
    	{
    		Animals = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IAnimal>(this);
    		Articles = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IArticle>(this);
    		BaseEntities = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IBaseEntity>(this);
    		Companies = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.ICompany>(this);
    		DBPediaPersons = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IDBPediaPerson>(this);
    		Departments = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IDepartment>(this);
    		DerivedEntities = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IDerivedEntity>(this);
    		Entities = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IEntity>(this);
    		FoafAgents = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IFoafAgent>(this);
    		FoafPersons = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IFoafPerson>(this);
    		IdentityClashTests = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IIdentityClashTest>(this);
    		IdentityClashTestLevel1s = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IIdentityClashTestLevel1>(this);
    		IdentityClashTestLevel2s = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IIdentityClashTestLevel2>(this);
    		JobRoles = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IJobRole>(this);
    		Markets = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IMarket>(this);
    		Persons = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IPerson>(this);
    		Sessions = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.ISession>(this);
    		EveningSessions = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.IEveningSession>(this);
    		TechnicalEveningSessions = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.ITechnicalEveningSession>(this);
    		Skills = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.ISkill>(this);
    		Trackables = 	new BrightstarEntitySet<BrightstarDB.Tests.EntityFramework.ITrackable>(this);
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IAnimal> Animals
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IArticle> Articles
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IBaseEntity> BaseEntities
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.ICompany> Companies
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IDBPediaPerson> DBPediaPersons
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IDepartment> Departments
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IDerivedEntity> DerivedEntities
    	{
    		get; private set;
    	}
    	
    	internal IEntitySet<BrightstarDB.Tests.EntityFramework.IEntity> Entities
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IFoafAgent> FoafAgents
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IFoafPerson> FoafPersons
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IIdentityClashTest> IdentityClashTests
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IIdentityClashTestLevel1> IdentityClashTestLevel1s
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IIdentityClashTestLevel2> IdentityClashTestLevel2s
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IJobRole> JobRoles
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IMarket> Markets
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IPerson> Persons
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.ISession> Sessions
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.IEveningSession> EveningSessions
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.ITechnicalEveningSession> TechnicalEveningSessions
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.ISkill> Skills
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Tests.EntityFramework.ITrackable> Trackables
    	{
    		get; private set;
    	}
    	
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class Animal : BrightstarEntityObject, IAnimal 
    {
    	public Animal(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public Animal() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IAnimal
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public BrightstarDB.Tests.EntityFramework.IPerson Owner
    	{
            get { return GetRelatedObject<BrightstarDB.Tests.EntityFramework.IPerson>("Owner"); }
            set { SetRelatedObject<BrightstarDB.Tests.EntityFramework.IPerson>("Owner", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class Article : BrightstarEntityObject, IArticle 
    {
    	public Article(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public Article() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IArticle
    
    	public System.String Title
    	{
            		get { return GetRelatedProperty<System.String>("Title"); }
            		set { SetRelatedProperty("Title", value); }
    	}
    
    	public System.String BodyText
    	{
            		get { return GetRelatedProperty<System.String>("BodyText"); }
            		set { SetRelatedProperty("BodyText", value); }
    	}
    
    	public BrightstarDB.Tests.EntityFramework.IPerson Publisher
    	{
            get { return GetRelatedObject<BrightstarDB.Tests.EntityFramework.IPerson>("Publisher"); }
            set { SetRelatedObject<BrightstarDB.Tests.EntityFramework.IPerson>("Publisher", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.Tests.EntityFramework.ITrackable
    
    	public System.DateTime Created
    	{
            		get { return GetRelatedProperty<System.DateTime>("Created"); }
            		set { SetRelatedProperty("Created", value); }
    	}
    
    	public System.DateTime LastModified
    	{
            		get { return GetRelatedProperty<System.DateTime>("LastModified"); }
            		set { SetRelatedProperty("LastModified", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class BaseEntity : BrightstarEntityObject, IBaseEntity 
    {
    	public BaseEntity(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public BaseEntity() : base() { }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IBaseEntity
    
    	public System.String BaseStringValue
    	{
            		get { return GetRelatedProperty<System.String>("BaseStringValue"); }
            		set { SetRelatedProperty("BaseStringValue", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class Company : BrightstarEntityObject, ICompany 
    {
    	public Company(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public Company() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.ICompany
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public System.String TickerSymbol
    	{
            		get { return GetRelatedProperty<System.String>("TickerSymbol"); }
            		set { SetRelatedProperty("TickerSymbol", value); }
    	}
    
    	public BrightstarDB.Tests.EntityFramework.IMarket ListedOn
    	{
            get { return GetRelatedObject<BrightstarDB.Tests.EntityFramework.IMarket>("ListedOn"); }
            set { SetRelatedObject<BrightstarDB.Tests.EntityFramework.IMarket>("ListedOn", value); }
    	}
    
    	public System.Decimal CurrentSharePrice
    	{
            		get { return GetRelatedProperty<System.Decimal>("CurrentSharePrice"); }
            		set { SetRelatedProperty("CurrentSharePrice", value); }
    	}
    
    	public System.Double CurrentMarketCap
    	{
            		get { return GetRelatedProperty<System.Double>("CurrentMarketCap"); }
            		set { SetRelatedProperty("CurrentMarketCap", value); }
    	}
    
    	public System.Int32 HeadCount
    	{
            		get { return GetRelatedProperty<System.Int32>("HeadCount"); }
            		set { SetRelatedProperty("HeadCount", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class DBPediaPerson : BrightstarEntityObject, IDBPediaPerson 
    {
    	public DBPediaPerson(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public DBPediaPerson() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IDBPediaPerson
    
    	public System.DateTime BirthDate
    	{
            		get { return GetRelatedProperty<System.DateTime>("BirthDate"); }
            		set { SetRelatedProperty("BirthDate", value); }
    	}
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public System.String GivenName
    	{
            		get { return GetRelatedProperty<System.String>("GivenName"); }
            		set { SetRelatedProperty("GivenName", value); }
    	}
    
    	public System.String Surname
    	{
            		get { return GetRelatedProperty<System.String>("Surname"); }
            		set { SetRelatedProperty("Surname", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class Department : BrightstarEntityObject, IDepartment 
    {
    	public Department(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public Department() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IDepartment
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public System.Int32 DeptId
    	{
            		get { return GetRelatedProperty<System.Int32>("DeptId"); }
            		set { SetRelatedProperty("DeptId", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Tests.EntityFramework.IPerson> Persons
    	{
    		get { return GetRelatedObjects<BrightstarDB.Tests.EntityFramework.IPerson>("Persons"); }
    		set { SetRelatedObjects("Persons", value); }
    								}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class DerivedEntity : BrightstarEntityObject, IDerivedEntity 
    {
    	public DerivedEntity(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public DerivedEntity() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IDerivedEntity
    
    	public System.DateTime DateTimeProperty
    	{
            		get { return GetRelatedProperty<System.DateTime>("DateTimeProperty"); }
            		set { SetRelatedProperty("DateTimeProperty", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Tests.EntityFramework.IBaseEntity> RelatedEntities
    	{
    		get { return GetRelatedObjects<BrightstarDB.Tests.EntityFramework.IBaseEntity>("RelatedEntities"); }
    		set { SetRelatedObjects("RelatedEntities", value); }
    								}
    	#endregion
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IBaseEntity
    
    	public System.String BaseStringValue
    	{
            		get { return GetRelatedProperty<System.String>("BaseStringValue"); }
            		set { SetRelatedProperty("BaseStringValue", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    internal partial class Entity : BrightstarEntityObject, IEntity 
    {
    	public Entity(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public Entity() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IEntity
    
    	public System.String SomeString
    	{
            		get { return GetRelatedProperty<System.String>("SomeString"); }
            		set { SetRelatedProperty("SomeString", value); }
    	}
    
    	public System.DateTime SomeDateTime
    	{
            		get { return GetRelatedProperty<System.DateTime>("SomeDateTime"); }
            		set { SetRelatedProperty("SomeDateTime", value); }
    	}
    
    	public System.Nullable<System.DateTime> SomeNullableDateTime
    	{
            		get { return GetRelatedProperty<System.Nullable<System.DateTime>>("SomeNullableDateTime"); }
            		set { SetRelatedProperty("SomeNullableDateTime", value); }
    	}
    
    	public System.Boolean SomeBool
    	{
            		get { return GetRelatedProperty<System.Boolean>("SomeBool"); }
            		set { SetRelatedProperty("SomeBool", value); }
    	}
    
    	public System.Nullable<System.Boolean> NullableBool
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Boolean>>("NullableBool"); }
            		set { SetRelatedProperty("NullableBool", value); }
    	}
    
    	public System.Byte SomeByte
    	{
            		get { return GetRelatedProperty<System.Byte>("SomeByte"); }
            		set { SetRelatedProperty("SomeByte", value); }
    	}
    
    	public System.Byte AnotherByte
    	{
            		get { return GetRelatedProperty<System.Byte>("AnotherByte"); }
            		set { SetRelatedProperty("AnotherByte", value); }
    	}
    
    	public System.Nullable<System.Byte> NullableByte
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Byte>>("NullableByte"); }
            		set { SetRelatedProperty("NullableByte", value); }
    	}
    
    	public System.Nullable<System.Byte> AnotherNullableByte
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Byte>>("AnotherNullableByte"); }
            		set { SetRelatedProperty("AnotherNullableByte", value); }
    	}
    
    	public System.Char SomeChar
    	{
            		get { return GetRelatedProperty<System.Char>("SomeChar"); }
            		set { SetRelatedProperty("SomeChar", value); }
    	}
    
    	public System.Char AnotherChar
    	{
            		get { return GetRelatedProperty<System.Char>("AnotherChar"); }
            		set { SetRelatedProperty("AnotherChar", value); }
    	}
    
    	public System.Nullable<System.Char> NullableChar
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Char>>("NullableChar"); }
            		set { SetRelatedProperty("NullableChar", value); }
    	}
    
    	public System.Nullable<System.Char> AnotherNullableChar
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Char>>("AnotherNullableChar"); }
            		set { SetRelatedProperty("AnotherNullableChar", value); }
    	}
    
    	public System.Decimal SomeDecimal
    	{
            		get { return GetRelatedProperty<System.Decimal>("SomeDecimal"); }
            		set { SetRelatedProperty("SomeDecimal", value); }
    	}
    
    	public System.Double SomeDouble
    	{
            		get { return GetRelatedProperty<System.Double>("SomeDouble"); }
            		set { SetRelatedProperty("SomeDouble", value); }
    	}
    
    	public System.Single SomeFloat
    	{
            		get { return GetRelatedProperty<System.Single>("SomeFloat"); }
            		set { SetRelatedProperty("SomeFloat", value); }
    	}
    
    	public System.Int32 SomeInt
    	{
            		get { return GetRelatedProperty<System.Int32>("SomeInt"); }
            		set { SetRelatedProperty("SomeInt", value); }
    	}
    
    	public System.Nullable<System.Int32> SomeNullableInt
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Int32>>("SomeNullableInt"); }
            		set { SetRelatedProperty("SomeNullableInt", value); }
    	}
    
    	public System.Int64 SomeLong
    	{
            		get { return GetRelatedProperty<System.Int64>("SomeLong"); }
            		set { SetRelatedProperty("SomeLong", value); }
    	}
    
    	public System.SByte SomeSByte
    	{
            		get { return GetRelatedProperty<System.SByte>("SomeSByte"); }
            		set { SetRelatedProperty("SomeSByte", value); }
    	}
    
    	public System.SByte AnotherSByte
    	{
            		get { return GetRelatedProperty<System.SByte>("AnotherSByte"); }
            		set { SetRelatedProperty("AnotherSByte", value); }
    	}
    
    	public System.Int16 SomeShort
    	{
            		get { return GetRelatedProperty<System.Int16>("SomeShort"); }
            		set { SetRelatedProperty("SomeShort", value); }
    	}
    
    	public System.Int16 AnotherShort
    	{
            		get { return GetRelatedProperty<System.Int16>("AnotherShort"); }
            		set { SetRelatedProperty("AnotherShort", value); }
    	}
    
    	public System.UInt32 SomeUInt
    	{
            		get { return GetRelatedProperty<System.UInt32>("SomeUInt"); }
            		set { SetRelatedProperty("SomeUInt", value); }
    	}
    
    	public System.UInt32 AnotherUInt
    	{
            		get { return GetRelatedProperty<System.UInt32>("AnotherUInt"); }
            		set { SetRelatedProperty("AnotherUInt", value); }
    	}
    
    	public System.UInt64 SomeULong
    	{
            		get { return GetRelatedProperty<System.UInt64>("SomeULong"); }
            		set { SetRelatedProperty("SomeULong", value); }
    	}
    
    	public System.UInt64 AnotherULong
    	{
            		get { return GetRelatedProperty<System.UInt64>("AnotherULong"); }
            		set { SetRelatedProperty("AnotherULong", value); }
    	}
    
    	public System.UInt16 SomeUShort
    	{
            		get { return GetRelatedProperty<System.UInt16>("SomeUShort"); }
            		set { SetRelatedProperty("SomeUShort", value); }
    	}
    
    	public System.UInt16 AnotherUShort
    	{
            		get { return GetRelatedProperty<System.UInt16>("AnotherUShort"); }
            		set { SetRelatedProperty("AnotherUShort", value); }
    	}
    
    	public System.Byte[] SomeByteArray
    	{
            		get { return GetRelatedProperty<System.Byte[]>("SomeByteArray"); }
            		set { SetRelatedProperty("SomeByteArray", value); }
    	}
    
    	public BrightstarDB.Tests.EntityFramework.TestEnumeration SomeEnumeration
    	{
            		get { return GetRelatedProperty<BrightstarDB.Tests.EntityFramework.TestEnumeration>("SomeEnumeration"); }
            		set { SetRelatedProperty("SomeEnumeration", value); }
    	}
    
    	public System.Nullable<BrightstarDB.Tests.EntityFramework.TestEnumeration> SomeNullableEnumeration
    	{
            		get { return GetRelatedProperty<System.Nullable<BrightstarDB.Tests.EntityFramework.TestEnumeration>>("SomeNullableEnumeration"); }
            		set { SetRelatedProperty("SomeNullableEnumeration", value); }
    	}
    
    	public BrightstarDB.Tests.EntityFramework.TestFlagsEnumeration SomeFlagsEnumeration
    	{
            		get { return GetRelatedProperty<BrightstarDB.Tests.EntityFramework.TestFlagsEnumeration>("SomeFlagsEnumeration"); }
            		set { SetRelatedProperty("SomeFlagsEnumeration", value); }
    	}
    
    	public System.Nullable<BrightstarDB.Tests.EntityFramework.TestFlagsEnumeration> SomeNullableFlagsEnumeration
    	{
            		get { return GetRelatedProperty<System.Nullable<BrightstarDB.Tests.EntityFramework.TestFlagsEnumeration>>("SomeNullableFlagsEnumeration"); }
            		set { SetRelatedProperty("SomeNullableFlagsEnumeration", value); }
    	}
    	public System.Collections.Generic.ICollection<System.String> CollectionOfStrings
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.String>("CollectionOfStrings"); }
    		set { SetRelatedLiteralPropertiesCollection<System.String>("CollectionOfStrings", value); }
    	}
    	public System.Collections.Generic.ICollection<System.DateTime> CollectionOfDateTimes
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.DateTime>("CollectionOfDateTimes"); }
    		set { SetRelatedLiteralPropertiesCollection<System.DateTime>("CollectionOfDateTimes", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Boolean> CollectionOfBools
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Boolean>("CollectionOfBools"); }
    		set { SetRelatedLiteralPropertiesCollection<System.Boolean>("CollectionOfBools", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Decimal> CollectionOfDecimals
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Decimal>("CollectionOfDecimals"); }
    		set { SetRelatedLiteralPropertiesCollection<System.Decimal>("CollectionOfDecimals", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Double> CollectionOfDoubles
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Double>("CollectionOfDoubles"); }
    		set { SetRelatedLiteralPropertiesCollection<System.Double>("CollectionOfDoubles", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Single> CollectionOfFloats
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Single>("CollectionOfFloats"); }
    		set { SetRelatedLiteralPropertiesCollection<System.Single>("CollectionOfFloats", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Int32> CollectionOfInts
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Int32>("CollectionOfInts"); }
    		set { SetRelatedLiteralPropertiesCollection<System.Int32>("CollectionOfInts", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Int64> CollectionOfLong
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Int64>("CollectionOfLong"); }
    		set { SetRelatedLiteralPropertiesCollection<System.Int64>("CollectionOfLong", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class FoafAgent : BrightstarEntityObject, IFoafAgent 
    {
    	public FoafAgent(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public FoafAgent() : base() { }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IFoafAgent
    	public System.Collections.Generic.ICollection<System.String> MboxSums
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.String>("MboxSums"); }
    		set { SetRelatedLiteralPropertiesCollection<System.String>("MboxSums", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    [DisplayName("Person")]
    public partial class FoafPerson : BrightstarEntityObject, IFoafPerson 
    {
    	public FoafPerson(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public FoafPerson() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IFoafPerson
    	
    	[System.ComponentModel.DisplayNameAttribute("Also Known As")]
    	public System.String Nickname
    	{
            		get { return GetRelatedProperty<System.String>("Nickname"); }
            		set { SetRelatedProperty("Nickname", value); }
    	}
    	
    	[System.ComponentModel.DataAnnotations.RequiredAttribute]	
    	[System.ComponentModel.DataAnnotations.CustomValidationAttribute(typeof(MyCustomValidator), "ValidateName", ErrorMessage="Custom error message")]
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public System.String Organisation
    	{
            		get { return GetRelatedProperty<System.String>("Organisation"); }
            		set { SetRelatedProperty("Organisation", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Tests.EntityFramework.IFoafPerson> Knows
    	{
    		get { return GetRelatedObjects<BrightstarDB.Tests.EntityFramework.IFoafPerson>("Knows"); }
    		set { SetRelatedObjects("Knows", value); }
    								}
    	public System.Collections.Generic.ICollection<BrightstarDB.Tests.EntityFramework.IFoafPerson> KnownBy
    	{
    		get { return GetRelatedObjects<BrightstarDB.Tests.EntityFramework.IFoafPerson>("KnownBy"); }
    		set { SetRelatedObjects("KnownBy", value); }
    								}
    	
    	[System.ComponentModel.DataAnnotations.DataTypeAttribute(DataType.Date)]
    	public System.Nullable<System.DateTime> BirthDate
    	{
            		get { return GetRelatedProperty<System.Nullable<System.DateTime>>("BirthDate"); }
            		set { SetRelatedProperty("BirthDate", value); }
    	}
    
    	public System.Uri Homepage
    	{
            		get { return GetRelatedProperty<System.Uri>("Homepage"); }
            		set { SetRelatedProperty("Homepage", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IFoafAgent
    	public System.Collections.Generic.ICollection<System.String> MboxSums
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.String>("MboxSums"); }
    		set { SetRelatedLiteralPropertiesCollection<System.String>("MboxSums", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class IdentityClashTest : BrightstarEntityObject, IIdentityClashTest 
    {
    	public IdentityClashTest(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public IdentityClashTest() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IIdentityClashTest
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class IdentityClashTestLevel1 : BrightstarEntityObject, IIdentityClashTestLevel1 
    {
    	public IdentityClashTestLevel1(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public IdentityClashTestLevel1() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IIdentityClashTestLevel1
    	#endregion
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IIdentityClashTest
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class IdentityClashTestLevel2 : BrightstarEntityObject, IIdentityClashTestLevel2 
    {
    	public IdentityClashTestLevel2(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public IdentityClashTestLevel2() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IIdentityClashTestLevel2
    	#endregion
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IIdentityClashTestLevel1
    	#endregion
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IIdentityClashTest
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class JobRole : BrightstarEntityObject, IJobRole 
    {
    	public JobRole(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public JobRole() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IJobRole
    
    	public System.String Description
    	{
            		get { return GetRelatedProperty<System.String>("Description"); }
            		set { SetRelatedProperty("Description", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Tests.EntityFramework.IPerson> Persons
    	{
    		get { return GetRelatedObjects<BrightstarDB.Tests.EntityFramework.IPerson>("Persons"); }
    		set { SetRelatedObjects("Persons", value); }
    								}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class Market : BrightstarEntityObject, IMarket 
    {
    	public Market(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public Market() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IMarket
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Tests.EntityFramework.ICompany> ListedCompanies
    	{
    		get { return GetRelatedObjects<BrightstarDB.Tests.EntityFramework.ICompany>("ListedCompanies"); }
    		set { SetRelatedObjects("ListedCompanies", value); }
    								}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class Person : BrightstarEntityObject, IPerson 
    {
    	public Person(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public Person() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IPerson
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public System.Nullable<System.DateTime> DateOfBirth
    	{
            		get { return GetRelatedProperty<System.Nullable<System.DateTime>>("DateOfBirth"); }
            		set { SetRelatedProperty("DateOfBirth", value); }
    	}
    
    	public System.Int32 Age
    	{
            		get { return GetRelatedProperty<System.Int32>("Age"); }
            		set { SetRelatedProperty("Age", value); }
    	}
    
    	public System.Int32 Salary
    	{
            		get { return GetRelatedProperty<System.Int32>("Salary"); }
            		set { SetRelatedProperty("Salary", value); }
    	}
    
    	public BrightstarDB.Tests.EntityFramework.IPerson Mother
    	{
            get { return GetRelatedObject<BrightstarDB.Tests.EntityFramework.IPerson>("Mother"); }
            set { SetRelatedObject<BrightstarDB.Tests.EntityFramework.IPerson>("Mother", value); }
    	}
    
    	public BrightstarDB.Tests.EntityFramework.IPerson Father
    	{
            get { return GetRelatedObject<BrightstarDB.Tests.EntityFramework.IPerson>("Father"); }
            set { SetRelatedObject<BrightstarDB.Tests.EntityFramework.IPerson>("Father", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Tests.EntityFramework.IPerson> Friends
    	{
    		get { return GetRelatedObjects<BrightstarDB.Tests.EntityFramework.IPerson>("Friends"); }
    		set { SetRelatedObjects("Friends", value); }
    								}
    
    	public BrightstarDB.Tests.EntityFramework.IAnimal Pet
    	{
            get { return GetRelatedObject<BrightstarDB.Tests.EntityFramework.IAnimal>("Pet"); }
            set { SetRelatedObject<BrightstarDB.Tests.EntityFramework.IAnimal>("Pet", value); }
    	}
    
    	public BrightstarDB.Tests.EntityFramework.ISkill MainSkill
    	{
            get { return GetRelatedObject<BrightstarDB.Tests.EntityFramework.ISkill>("MainSkill"); }
            set { SetRelatedObject<BrightstarDB.Tests.EntityFramework.ISkill>("MainSkill", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Tests.EntityFramework.ISkill> Skills
    	{
    		get { return GetRelatedObjects<BrightstarDB.Tests.EntityFramework.ISkill>("Skills"); }
    		set { SetRelatedObjects("Skills", value); }
    								}
    
    	public BrightstarDB.Tests.EntityFramework.IDepartment Department
    	{
            get { return GetRelatedObject<BrightstarDB.Tests.EntityFramework.IDepartment>("Department"); }
            set { SetRelatedObject<BrightstarDB.Tests.EntityFramework.IDepartment>("Department", value); }
    	}
    
    	public System.Int32 EmployeeId
    	{
            		get { return GetRelatedProperty<System.Int32>("EmployeeId"); }
            		set { SetRelatedProperty("EmployeeId", value); }
    	}
    
    	public BrightstarDB.Tests.EntityFramework.IJobRole JobRole
    	{
            get { return GetRelatedObject<BrightstarDB.Tests.EntityFramework.IJobRole>("JobRole"); }
            set { SetRelatedObject<BrightstarDB.Tests.EntityFramework.IJobRole>("JobRole", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Uri> Websites
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Uri>("Websites"); }
    		set { SetRelatedLiteralPropertiesCollection<System.Uri>("Websites", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class Session : BrightstarEntityObject, ISession 
    {
    	public Session(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public Session() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.ISession
    
    	public System.String Speaker
    	{
            		get { return GetRelatedProperty<System.String>("Speaker"); }
            		set { SetRelatedProperty("Speaker", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class EveningSession : BrightstarEntityObject, IEveningSession 
    {
    	public EveningSession(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public EveningSession() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IEveningSession
    
    	public System.String DateTime
    	{
            		get { return GetRelatedProperty<System.String>("DateTime"); }
            		set { SetRelatedProperty("DateTime", value); }
    	}
    
    	public System.Boolean FreeBeer
    	{
            		get { return GetRelatedProperty<System.Boolean>("FreeBeer"); }
            		set { SetRelatedProperty("FreeBeer", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.Tests.EntityFramework.ISession
    
    	public System.String Speaker
    	{
            		get { return GetRelatedProperty<System.String>("Speaker"); }
            		set { SetRelatedProperty("Speaker", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class TechnicalEveningSession : BrightstarEntityObject, ITechnicalEveningSession 
    {
    	public TechnicalEveningSession(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public TechnicalEveningSession() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.ITechnicalEveningSession
    
    	public System.String Subject
    	{
            		get { return GetRelatedProperty<System.String>("Subject"); }
            		set { SetRelatedProperty("Subject", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.Tests.EntityFramework.IEveningSession
    
    	public System.String DateTime
    	{
            		get { return GetRelatedProperty<System.String>("DateTime"); }
            		set { SetRelatedProperty("DateTime", value); }
    	}
    
    	public System.Boolean FreeBeer
    	{
            		get { return GetRelatedProperty<System.Boolean>("FreeBeer"); }
            		set { SetRelatedProperty("FreeBeer", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.Tests.EntityFramework.ISession
    
    	public System.String Speaker
    	{
            		get { return GetRelatedProperty<System.String>("Speaker"); }
            		set { SetRelatedProperty("Speaker", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class Skill : BrightstarEntityObject, ISkill 
    {
    	public Skill(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public Skill() : base() { }
    	public System.String Id { get {return GetIdentity(); } set { SetIdentity(value); } }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.ISkill
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public BrightstarDB.Tests.EntityFramework.IPerson Expert
    	{
            get { return GetRelatedObject<BrightstarDB.Tests.EntityFramework.IPerson>("Expert"); }
            set { SetRelatedObject<BrightstarDB.Tests.EntityFramework.IPerson>("Expert", value); }
    	}
    
    	public BrightstarDB.Tests.EntityFramework.ISkill Parent
    	{
            get { return GetRelatedObject<BrightstarDB.Tests.EntityFramework.ISkill>("Parent"); }
            set { SetRelatedObject<BrightstarDB.Tests.EntityFramework.ISkill>("Parent", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Tests.EntityFramework.ISkill> Children
    	{
    		get { return GetRelatedObjects<BrightstarDB.Tests.EntityFramework.ISkill>("Children"); }
    		set { SetRelatedObjects("Children", value); }
    								}
    	public System.Collections.Generic.ICollection<BrightstarDB.Tests.EntityFramework.IPerson> SkilledPeople
    	{
    		get { return GetRelatedObjects<BrightstarDB.Tests.EntityFramework.IPerson>("SkilledPeople"); }
    		set { SetRelatedObjects("SkilledPeople", value); }
    								}
    	#endregion
    }
}
namespace BrightstarDB.Tests.EntityFramework 
{
    
    public partial class Trackable : BrightstarEntityObject, ITrackable 
    {
    	public Trackable(BrightstarEntityContext context, IDataObject dataObject) : base(context, dataObject) { }
    	public Trackable() : base() { }
    	#region Implementation of BrightstarDB.Tests.EntityFramework.ITrackable
    
    	public System.DateTime Created
    	{
            		get { return GetRelatedProperty<System.DateTime>("Created"); }
            		set { SetRelatedProperty("Created", value); }
    	}
    
    	public System.DateTime LastModified
    	{
            		get { return GetRelatedProperty<System.DateTime>("LastModified"); }
            		set { SetRelatedProperty("LastModified", value); }
    	}
    	#endregion
    }
}
