//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightstarDB.Client
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClusterDescription", Namespace="http://schemas.datacontract.org/2004/07/BrightstarDB.ClusterManager")]
    internal partial class ClusterDescription : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime LastUpdatedField;
        
        private System.Uri MasterHttpAddressField;
        
        private System.Uri MasterTcpAddressField;
        
        private System.Uri[] SlaveHttpAddressesField;
        
        private System.Uri[] SlaveTcpAddressesField;
        
        private BrightstarDB.Client.ClusterStatus StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.DateTime LastUpdated
        {
            get
            {
                return this.LastUpdatedField;
            }
            set
            {
                this.LastUpdatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Uri MasterHttpAddress
        {
            get
            {
                return this.MasterHttpAddressField;
            }
            set
            {
                this.MasterHttpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Uri MasterTcpAddress
        {
            get
            {
                return this.MasterTcpAddressField;
            }
            set
            {
                this.MasterTcpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Uri[] SlaveHttpAddresses
        {
            get
            {
                return this.SlaveHttpAddressesField;
            }
            set
            {
                this.SlaveHttpAddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Uri[] SlaveTcpAddresses
        {
            get
            {
                return this.SlaveTcpAddressesField;
            }
            set
            {
                this.SlaveTcpAddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal BrightstarDB.Client.ClusterStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClusterStatus", Namespace="http://schemas.datacontract.org/2004/07/BrightstarDB.ClusterManager")]
    internal enum ClusterStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unavailable = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReadOnly = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Available = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://brightstardb.com/services/cluster/management", ConfigurationName="BrightstarDB.Client.IBrightstarClusertManagerService")]
    internal interface IBrightstarClusertManagerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brightstardb.com/services/cluster/management/IBrightstarClusertManagerServ" +
            "ice/GetClusterDescription", ReplyAction="http://brightstardb.com/services/cluster/management/IBrightstarClusertManagerServ" +
            "ice/GetClusterDescriptionResponse")]
        BrightstarDB.Client.ClusterDescription GetClusterDescription();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IBrightstarClusertManagerServiceChannel : BrightstarDB.Client.IBrightstarClusertManagerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class BrightstarClusertManagerServiceClient : System.ServiceModel.ClientBase<BrightstarDB.Client.IBrightstarClusertManagerService>, BrightstarDB.Client.IBrightstarClusertManagerService
    {
        
        public BrightstarClusertManagerServiceClient()
        {
        }
        
        public BrightstarClusertManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public BrightstarClusertManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BrightstarClusertManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BrightstarClusertManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public BrightstarDB.Client.ClusterDescription GetClusterDescription()
        {
            return base.Channel.GetClusterDescription();
        }
    }
}
