//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("1.2.0.0")]
[assembly: AssemblyFileVersion("1.2.40221")]
[assembly: AssemblyProduct("BrightstarDB")]
[assembly: AssemblyCompany("BrightstarDB Limited")]
[assembly: AssemblyCopyright("Copyright (c) BrightstarDB Limited 2012")]
[assembly: AssemblyTrademark("All rights reserved")]
[assembly: AssemblyTitle("BrightstarDB WCF Service Assembly")]


