//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using BrightstarDB.Azure.Common;

namespace BrightstarDB.Azure.StoreWorkerClient
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.networkedplanet.com/services/brightstar/azureblockupdateservice", ConfigurationName="NetworkedPlanet.Brightstar.Azure.StoreWorkerClient.IBlockUpdateService")]
    public interface IBlockUpdateService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.networkedplanet.com/services/brightstar/azureblockupdateservice/IBlock" +
            "UpdateService/UpdateBlock", ReplyAction="http://www.networkedplanet.com/services/brightstar/azureblockupdateservice/IBlock" +
            "UpdateService/UpdateBlockResponse")]
        void UpdateBlock(BlockInfo block);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlockUpdateServiceChannel : IBlockUpdateService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlockUpdateServiceClient : System.ServiceModel.ClientBase<IBlockUpdateService>, IBlockUpdateService
    {
        
        public BlockUpdateServiceClient()
        {
        }
        
        public BlockUpdateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public BlockUpdateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BlockUpdateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BlockUpdateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void UpdateBlock(BlockInfo block)
        {
            base.Channel.UpdateBlock(block);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/", ConfigurationName="NetworkedPlanet.Brightstar.Azure.StoreWorkerClient.IStoreWorkerService")]
    public interface IStoreWorkerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/IStore" +
            "WorkerService/CreateStore", ReplyAction="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/IStore" +
            "WorkerService/CreateStoreResponse")]
        bool CreateStore(string storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/IStore" +
            "WorkerService/ExecuteQuery", ReplyAction="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/IStore" +
            "WorkerService/ExecuteQueryResponse")]
        string ExecuteQuery(string storeId, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/IStore" +
            "WorkerService/DeleteStore", ReplyAction="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/IStore" +
            "WorkerService/DeleteStoreResponse")]
        bool DeleteStore(string storeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreWorkerServiceChannel : IStoreWorkerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreWorkerServiceClient : System.ServiceModel.ClientBase<IStoreWorkerService>, IStoreWorkerService
    {
        
        public StoreWorkerServiceClient()
        {
        }
        
        public StoreWorkerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public StoreWorkerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public StoreWorkerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public StoreWorkerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool CreateStore(string storeId)
        {
            return base.Channel.CreateStore(storeId);
        }
        
        public string ExecuteQuery(string storeId, string query)
        {
            return base.Channel.ExecuteQuery(storeId, query);
        }
        
        public bool DeleteStore(string storeId)
        {
            return base.Channel.DeleteStore(storeId);
        }
    }
}
