//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightstarDB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrightstarDB.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit point must not be NULL..
        /// </summary>
        internal static string BrightstarServiceClient_CommitPointMustNotBeNull {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_CommitPointMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export file name must not be an empty string..
        /// </summary>
        internal static string BrightstarServiceClient_ExportFileNameMustNotBeEmptyString {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_ExportFileNameMustNotBeEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export file name must not be NULL..
        /// </summary>
        internal static string BrightstarServiceClient_ExportFileNameMustNotBeNull {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_ExportFileNameMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested number of commit points exceeds maximum value of 100..
        /// </summary>
        internal static string BrightstarServiceClient_GetCommitPoints_TakeToLarge {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_GetCommitPoints_TakeToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested number of statistics records exceeds the maximum value of 100..
        /// </summary>
        internal static string BrightstarServiceClient_GetStatistics_TakeTooLarge {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_GetStatistics_TakeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file name must not be an empty string..
        /// </summary>
        internal static string BrightstarServiceClient_ImportFileNameMustNotBeEmptyString {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_ImportFileNameMustNotBeEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file name must not be NULL..
        /// </summary>
        internal static string BrightstarServiceClient_ImportFileNameMustNotBeNull {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_ImportFileNameMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid commit point info object.
        /// </summary>
        internal static string BrightstarServiceClient_InvalidCommitPointInfoObject {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_InvalidCommitPointInfoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid store name. Store name may only include letters, digits or the following punctuation characters: -_.+,().
        /// </summary>
        internal static string BrightstarServiceClient_InvalidStoreName {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_InvalidStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction info object.
        /// </summary>
        internal static string BrightstarServiceClient_InvalidTransactionInfoObject {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_InvalidTransactionInfoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Id must not be an empty string..
        /// </summary>
        internal static string BrightstarServiceClient_JobIdMustNotBeEmptyString {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_JobIdMustNotBeEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Id must not be NULL..
        /// </summary>
        internal static string BrightstarServiceClient_JobIdMustNotBeNull {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_JobIdMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the connection string configuration information. Please check that the application configuration file contains the required appSettings elements..
        /// </summary>
        internal static string BrightstarServiceClient_NoConnectionStringConfiguration {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_NoConnectionStringConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default graph URI must not be NULL..
        /// </summary>
        internal static string BrightstarServiceClient_QueryDefaultGraphUriMustNotBeNull {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_QueryDefaultGraphUriMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query expression must not be an empty string..
        /// </summary>
        internal static string BrightstarServiceClient_QueryMustNotBeEmptyString {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_QueryMustNotBeEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query expression must not be NULL..
        /// </summary>
        internal static string BrightstarServiceClient_QueryMustNotBeNull {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_QueryMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip value must be a non-negative integer..
        /// </summary>
        internal static string BrightstarServiceClient_SkipMustNotBeNegative {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_SkipMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store name must not be an empty string..
        /// </summary>
        internal static string BrightstarServiceClient_StoreNameMustNotBeEmptyString {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_StoreNameMustNotBeEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store name must not be NULL..
        /// </summary>
        internal static string BrightstarServiceClient_StoreNameMustNotBeNull {
            get {
                return ResourceManager.GetString("BrightstarServiceClient_StoreNameMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to write to a fixed page..
        /// </summary>
        internal static string INode_Attempt_to_write_to_a_fixed_page {
            get {
                return ResourceManager.GetString("INode_Attempt_to_write_to_a_fixed_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity is not a valid URI nor CURIE with regards to the current namespace mappings..
        /// </summary>
        internal static string InvalidDataObjectIdentity {
            get {
                return ResourceManager.GetString("InvalidDataObjectIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value provided must be an instance of the type {0} or of a type derived from it..
        /// </summary>
        internal static string InvalidEntityType {
            get {
                return ResourceManager.GetString("InvalidEntityType", resourceCulture);
            }
        }
    }
}
