//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkedPlanet.Brightstar.Azure.Common
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.networkedplanet.com/services/brightstar/azureblockupdateservice", ConfigurationName="NetworkedPlanet.Brightstar.Azure.Common.IBlockUpdateService")]
    public interface IBlockUpdateService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.networkedplanet.com/services/brightstar/azureblockupdateservice/IBlock" +
            "UpdateService/UpdateBlock", ReplyAction="http://www.networkedplanet.com/services/brightstar/azureblockupdateservice/IBlock" +
            "UpdateService/UpdateBlockResponse")]
        void UpdateBlock(NetworkedPlanet.Brightstar.Azure.Common.BlockInfo block);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlockUpdateServiceChannel : NetworkedPlanet.Brightstar.Azure.Common.IBlockUpdateService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlockUpdateServiceClient : System.ServiceModel.ClientBase<NetworkedPlanet.Brightstar.Azure.Common.IBlockUpdateService>, NetworkedPlanet.Brightstar.Azure.Common.IBlockUpdateService
    {
        
        public BlockUpdateServiceClient()
        {
        }
        
        public BlockUpdateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public BlockUpdateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BlockUpdateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BlockUpdateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void UpdateBlock(NetworkedPlanet.Brightstar.Azure.Common.BlockInfo block)
        {
            base.Channel.UpdateBlock(block);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/", ConfigurationName="NetworkedPlanet.Brightstar.Azure.Common.IStoreWorkerService")]
    public interface IStoreWorkerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/IStore" +
            "WorkerService/CreateStore", ReplyAction="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/IStore" +
            "WorkerService/CreateStoreResponse")]
        bool CreateStore(string storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/IStore" +
            "WorkerService/ExecuteQuery", ReplyAction="http://www.networkedplanet.com/services/brightstar/azurestoreworkerservice/IStore" +
            "WorkerService/ExecuteQueryResponse")]
        string ExecuteQuery(string storeId, string query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreWorkerServiceChannel : NetworkedPlanet.Brightstar.Azure.Common.IStoreWorkerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreWorkerServiceClient : System.ServiceModel.ClientBase<NetworkedPlanet.Brightstar.Azure.Common.IStoreWorkerService>, NetworkedPlanet.Brightstar.Azure.Common.IStoreWorkerService
    {
        
        public StoreWorkerServiceClient()
        {
        }
        
        public StoreWorkerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public StoreWorkerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public StoreWorkerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public StoreWorkerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool CreateStore(string storeId)
        {
            return base.Channel.CreateStore(storeId);
        }
        
        public string ExecuteQuery(string storeId, string query)
        {
            return base.Channel.ExecuteQuery(storeId, query);
        }
    }
}
