// -----------------------------------------------------------------------
// <autogenerated>
//    This code was generated from a template.
// 
//    Changes to this file may cause incorrect behaviour and will be lost
//    if the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------
namespace FoafCore
{
    [System.CodeDom.Compiler.GeneratedCode("BrightstarDB.CodeGeneration", "0.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class EntityContext : global::BrightstarDB.EntityFramework.BrightstarEntityContext
    {
        static EntityContext()
        {
            var provider = new global::BrightstarDB.EntityFramework.ReflectionMappingProvider();
            provider.AddMappingsForType(global::BrightstarDB.EntityFramework.EntityMappingStore.Instance, typeof(global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson));
            global::BrightstarDB.EntityFramework.EntityMappingStore.Instance.SetImplMapping<global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson, BrightstarDB.Samples.EntityFramework.FoafCore.Person>();
        }

        public EntityContext()
        {
            this.InitializeContext();
        }

        public EntityContext(global::BrightstarDB.Client.IDataObjectStore dataObjectStore) : base(dataObjectStore)
        {
            this.InitializeContext();
        }

        public EntityContext(string updateGraphUri, global::System.Collections.Generic.IEnumerable<global::System.String> datasetGraphUris, string versionGraphUri) : base(updateGraphUri, datasetGraphUris, versionGraphUri)
        {
            this.InitializeContext();
        }

        public EntityContext(string connectionString, global::System.Boolean? enableOptimisticLocking = null, string updateGraphUri = null, global::System.Collections.Generic.IEnumerable<global::System.String> datasetGraphUris = null, string versionGraphUri = null) : base(connectionString, enableOptimisticLocking, updateGraphUri, datasetGraphUris, versionGraphUri)
        {
            this.InitializeContext();
        }

        private void InitializeContext()
        {
            this._Persons = (new global::BrightstarDB.EntityFramework.BrightstarEntitySet<global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson>(this));
        }

        public global::BrightstarDB.EntityFramework.IEntitySet<T> EntitySet<T>()
            where T : class
        {
            global::System.Type type = typeof(T);
            if (type.Equals(typeof(global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson)))
            {
                return (global::BrightstarDB.EntityFramework.IEntitySet<T>)(this.Persons);
            }

            throw new global::System.InvalidOperationException(((typeof(T)).FullName) + (" is not a recognized entity interface type."));
        }

        private global::BrightstarDB.EntityFramework.IEntitySet<global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson> _Persons;
        public global::BrightstarDB.EntityFramework.IEntitySet<global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson> Persons
        {
            get
            {
                return this._Persons;
            }
        }
    }
}
namespace BrightstarDB.Samples.EntityFramework.FoafCore
{
    [System.CodeDom.Compiler.GeneratedCode("BrightstarDB.CodeGeneration", "0.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class Person : global::BrightstarDB.EntityFramework.BrightstarEntityObject, global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson
    {
        public Person()
        {
        }

        public Person(global::BrightstarDB.EntityFramework.BrightstarEntityContext context) : base(context, typeof(Person))
        {
        }

        public Person(global::BrightstarDB.EntityFramework.BrightstarEntityContext context, global::BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject)
        {
        }

        public global::System.String Id
        {
            get
            {
                return base.GetKey();
            }

            set
            {
                base.SetKey(value);
            }
        }

        public global::System.String Nickname
        {
            get
            {
                return base.GetRelatedProperty<global::System.String>("Nickname");
            }

            set
            {
                base.SetRelatedProperty("Nickname", value);
            }
        }

        public global::System.String Name
        {
            get
            {
                return base.GetRelatedProperty<global::System.String>("Name");
            }

            set
            {
                base.SetRelatedProperty("Name", value);
            }
        }

        public global::System.String Organisation
        {
            get
            {
                return base.GetRelatedProperty<global::System.String>("Organisation");
            }

            set
            {
                base.SetRelatedProperty("Organisation", value);
            }
        }

        public global::System.Collections.Generic.ICollection<global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson> Knows
        {
            get
            {
                return base.GetRelatedObjects<global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson>("Knows");
            }

            set
            {
                if ((value) == (null))
                {
                    throw new global::System.ArgumentNullException("value");
                }

                base.SetRelatedObjects<global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson>("Knows", value);
            }
        }

        public global::System.Collections.Generic.ICollection<global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson> KnownBy
        {
            get
            {
                return base.GetRelatedObjects<global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson>("KnownBy");
            }

            set
            {
                if ((value) == (null))
                {
                    throw new global::System.ArgumentNullException("value");
                }

                base.SetRelatedObjects<global::BrightstarDB.Samples.EntityFramework.FoafCore.IPerson>("KnownBy", value);
            }
        }
    }
}
