 

// -----------------------------------------------------------------------
// <autogenerated>
//    This code was generated from a template.
//
//    Changes to this file may cause incorrect behaviour and will be lost
//    if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using BrightstarDB.Client;
using BrightstarDB.EntityFramework;

using System.ComponentModel;
using BrightstarDB.Rdf;
using System.ComponentModel.DataAnnotations;

namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    public partial class MyEntityContext : BrightstarEntityContext {
    	
    	static MyEntityContext() 
    	{
    		var provider = new ReflectionMappingProvider();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IAnimal));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IAnimal, BrightstarDB.Portable.Tests.EntityFramework.Model.Animal>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IArticle));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IArticle, BrightstarDB.Portable.Tests.EntityFramework.Model.Article>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity, BrightstarDB.Portable.Tests.EntityFramework.Model.BaseEntity>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IChildKeyEntity));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IChildKeyEntity, BrightstarDB.Portable.Tests.EntityFramework.Model.ChildKeyEntity>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ICompany));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.ICompany, BrightstarDB.Portable.Tests.EntityFramework.Model.Company>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ICompositeKeyEntity));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.ICompositeKeyEntity, BrightstarDB.Portable.Tests.EntityFramework.Model.CompositeKeyEntity>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IConcept));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IConcept, BrightstarDB.Portable.Tests.EntityFramework.Model.Concept>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IDBPediaPerson));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IDBPediaPerson, BrightstarDB.Portable.Tests.EntityFramework.Model.DBPediaPerson>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IDepartment));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IDepartment, BrightstarDB.Portable.Tests.EntityFramework.Model.Department>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IDerivedEntity));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IDerivedEntity, BrightstarDB.Portable.Tests.EntityFramework.Model.DerivedEntity>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IEntity));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IEntity, BrightstarDB.Portable.Tests.EntityFramework.Model.Entity>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafAgent));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafAgent, BrightstarDB.Portable.Tests.EntityFramework.Model.FoafAgent>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafPerson));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafPerson, BrightstarDB.Portable.Tests.EntityFramework.Model.FoafPerson>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IHierarchicalKeyEntity));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IHierarchicalKeyEntity, BrightstarDB.Portable.Tests.EntityFramework.Model.HierarchicalKeyEntity>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTest));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTest, BrightstarDB.Portable.Tests.EntityFramework.Model.IdentityClashTest>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel1));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel1, BrightstarDB.Portable.Tests.EntityFramework.Model.IdentityClashTestLevel1>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel2));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel2, BrightstarDB.Portable.Tests.EntityFramework.Model.IdentityClashTestLevel2>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IJobRole));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IJobRole, BrightstarDB.Portable.Tests.EntityFramework.Model.JobRole>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ILowerKeyEntity));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.ILowerKeyEntity, BrightstarDB.Portable.Tests.EntityFramework.Model.LowerKeyEntity>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IMarket));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IMarket, BrightstarDB.Portable.Tests.EntityFramework.Model.Market>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson, BrightstarDB.Portable.Tests.EntityFramework.Model.Person>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ISession));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.ISession, BrightstarDB.Portable.Tests.EntityFramework.Model.Session>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IEveningSession));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IEveningSession, BrightstarDB.Portable.Tests.EntityFramework.Model.EveningSession>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ITechnicalEveningSession));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.ITechnicalEveningSession, BrightstarDB.Portable.Tests.EntityFramework.Model.TechnicalEveningSession>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill, BrightstarDB.Portable.Tests.EntityFramework.Model.Skill>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IStringKeyEntity));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.IStringKeyEntity, BrightstarDB.Portable.Tests.EntityFramework.Model.StringKeyEntity>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ITrackable));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.Portable.Tests.EntityFramework.Model.ITrackable, BrightstarDB.Portable.Tests.EntityFramework.Model.Trackable>();
    	}
    	
    	/// <summary>
    	/// Initialize a new entity context using the specified BrightstarDB
    	/// Data Object Store connection
    	/// </summary>
    	/// <param name="dataObjectStore">The connection to the BrightstarDB Data Object Store that will provide the entity objects</param>
    	public MyEntityContext(IDataObjectStore dataObjectStore) : base(dataObjectStore)
    	{
    		InitializeContext();
    	}
    
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar connection string
    	/// </summary>
    	/// <param name="connectionString">The connection to be used to connect to an existing BrightstarDB store</param>
    	/// <param name="enableOptimisticLocking">OPTIONAL: If set to true optmistic locking will be applied to all entity updates</param>
        /// <param name="updateGraphUri">OPTIONAL: The URI identifier of the graph to be updated with any new triples created by operations on the store. If
        /// not defined, the default graph in the store will be updated.</param>
        /// <param name="datasetGraphUris">OPTIONAL: The URI identifiers of the graphs that will be queried to retrieve entities and their properties.
        /// If not defined, all graphs in the store will be queried.</param>
        /// <param name="versionGraphUri">OPTIONAL: The URI identifier of the graph that contains version number statements for entities. 
        /// If not defined, the <paramref name="updateGraphUri"/> will be used.</param>
    	public MyEntityContext(
    	    string connectionString, 
    		bool? enableOptimisticLocking=null,
    		string updateGraphUri = null,
    		IEnumerable<string> datasetGraphUris = null,
    		string versionGraphUri = null
        ) : base(connectionString, enableOptimisticLocking, updateGraphUri, datasetGraphUris, versionGraphUri)
    	{
    		InitializeContext();
    	}
    
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar
    	/// connection string retrieved from the configuration.
    	/// </summary>
    	public MyEntityContext() : base()
    	{
    		InitializeContext();
    	}
    	
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar
    	/// connection string retrieved from the configuration and the
    	//  specified target graphs
    	/// </summary>
        /// <param name="updateGraphUri">The URI identifier of the graph to be updated with any new triples created by operations on the store. If
        /// set to null, the default graph in the store will be updated.</param>
        /// <param name="datasetGraphUris">The URI identifiers of the graphs that will be queried to retrieve entities and their properties.
        /// If set to null, all graphs in the store will be queried.</param>
        /// <param name="versionGraphUri">The URI identifier of the graph that contains version number statements for entities. 
        /// If set to null, the value of <paramref name="updateGraphUri"/> will be used.</param>
    	public MyEntityContext(
    		string updateGraphUri,
    		IEnumerable<string> datasetGraphUris,
    		string versionGraphUri
    	) : base(updateGraphUri:updateGraphUri, datasetGraphUris:datasetGraphUris, versionGraphUri:versionGraphUri)
    	{
    		InitializeContext();
    	}
    	
    	private void InitializeContext() 
    	{
    		Animals = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IAnimal>(this);
    		Articles = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IArticle>(this);
    		BaseEntities = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity>(this);
    		ChildKeyEntities = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IChildKeyEntity>(this);
    		Companies = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ICompany>(this);
    		CompositeKeyEntities = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ICompositeKeyEntity>(this);
    		Concepts = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IConcept>(this);
    		DBPediaPersons = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IDBPediaPerson>(this);
    		Departments = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IDepartment>(this);
    		DerivedEntities = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IDerivedEntity>(this);
    		Entities = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IEntity>(this);
    		FoafAgents = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafAgent>(this);
    		FoafPersons = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafPerson>(this);
    		HierarchicalKeyEntities = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IHierarchicalKeyEntity>(this);
    		IdentityClashTests = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTest>(this);
    		IdentityClashTestLevel1s = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel1>(this);
    		IdentityClashTestLevel2s = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel2>(this);
    		JobRoles = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IJobRole>(this);
    		LowerKeyEntities = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ILowerKeyEntity>(this);
    		Markets = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IMarket>(this);
    		Persons = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>(this);
    		Sessions = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ISession>(this);
    		EveningSessions = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IEveningSession>(this);
    		TechnicalEveningSessions = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ITechnicalEveningSession>(this);
    		Skills = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill>(this);
    		StringKeyEntities = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IStringKeyEntity>(this);
    		Trackables = 	new BrightstarEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ITrackable>(this);
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IAnimal> Animals
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IArticle> Articles
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity> BaseEntities
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IChildKeyEntity> ChildKeyEntities
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ICompany> Companies
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ICompositeKeyEntity> CompositeKeyEntities
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IConcept> Concepts
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IDBPediaPerson> DBPediaPersons
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IDepartment> Departments
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IDerivedEntity> DerivedEntities
    	{
    		get; private set;
    	}
    	
    	internal IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IEntity> Entities
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafAgent> FoafAgents
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafPerson> FoafPersons
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IHierarchicalKeyEntity> HierarchicalKeyEntities
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTest> IdentityClashTests
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel1> IdentityClashTestLevel1s
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel2> IdentityClashTestLevel2s
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IJobRole> JobRoles
    	{
    		get; private set;
    	}
    	
    	internal IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ILowerKeyEntity> LowerKeyEntities
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IMarket> Markets
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson> Persons
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ISession> Sessions
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IEveningSession> EveningSessions
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ITechnicalEveningSession> TechnicalEveningSessions
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill> Skills
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.IStringKeyEntity> StringKeyEntities
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.Portable.Tests.EntityFramework.Model.ITrackable> Trackables
    	{
    		get; private set;
    	}
    	
        public IEntitySet<T> EntitySet<T>() where T : class {
            var itemType = typeof(T);
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IAnimal))) {
                return (IEntitySet<T>)this.Animals;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IArticle))) {
                return (IEntitySet<T>)this.Articles;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity))) {
                return (IEntitySet<T>)this.BaseEntities;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IChildKeyEntity))) {
                return (IEntitySet<T>)this.ChildKeyEntities;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ICompany))) {
                return (IEntitySet<T>)this.Companies;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ICompositeKeyEntity))) {
                return (IEntitySet<T>)this.CompositeKeyEntities;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IConcept))) {
                return (IEntitySet<T>)this.Concepts;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IDBPediaPerson))) {
                return (IEntitySet<T>)this.DBPediaPersons;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IDepartment))) {
                return (IEntitySet<T>)this.Departments;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IDerivedEntity))) {
                return (IEntitySet<T>)this.DerivedEntities;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IEntity))) {
                return (IEntitySet<T>)this.Entities;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafAgent))) {
                return (IEntitySet<T>)this.FoafAgents;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafPerson))) {
                return (IEntitySet<T>)this.FoafPersons;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IHierarchicalKeyEntity))) {
                return (IEntitySet<T>)this.HierarchicalKeyEntities;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTest))) {
                return (IEntitySet<T>)this.IdentityClashTests;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel1))) {
                return (IEntitySet<T>)this.IdentityClashTestLevel1s;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel2))) {
                return (IEntitySet<T>)this.IdentityClashTestLevel2s;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IJobRole))) {
                return (IEntitySet<T>)this.JobRoles;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ILowerKeyEntity))) {
                return (IEntitySet<T>)this.LowerKeyEntities;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IMarket))) {
                return (IEntitySet<T>)this.Markets;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson))) {
                return (IEntitySet<T>)this.Persons;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ISession))) {
                return (IEntitySet<T>)this.Sessions;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IEveningSession))) {
                return (IEntitySet<T>)this.EveningSessions;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ITechnicalEveningSession))) {
                return (IEntitySet<T>)this.TechnicalEveningSessions;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill))) {
                return (IEntitySet<T>)this.Skills;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.IStringKeyEntity))) {
                return (IEntitySet<T>)this.StringKeyEntities;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.Portable.Tests.EntityFramework.Model.ITrackable))) {
                return (IEntitySet<T>)this.Trackables;
            }
            throw new InvalidOperationException(typeof(T).FullName + " is not a recognized entity interface type.");
        }
    
        } // end class MyEntityContext
        
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class Animal : BrightstarEntityObject, IAnimal 
    {
    	public Animal(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Animal(BrightstarEntityContext context) : base(context, typeof(Animal)) { }
    	public Animal() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IAnimal
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson Owner
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Owner"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Owner", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class Article : BrightstarEntityObject, IArticle 
    {
    	public Article(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Article(BrightstarEntityContext context) : base(context, typeof(Article)) { }
    	public Article() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IArticle
    
    	public System.String Title
    	{
            		get { return GetRelatedProperty<System.String>("Title"); }
            		set { SetRelatedProperty("Title", value); }
    	}
    
    	public System.String BodyText
    	{
            		get { return GetRelatedProperty<System.String>("BodyText"); }
            		set { SetRelatedProperty("BodyText", value); }
    	}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson Publisher
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Publisher"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Publisher", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.ITrackable
    
    	public System.DateTime Created
    	{
            		get { return GetRelatedProperty<System.DateTime>("Created"); }
            		set { SetRelatedProperty("Created", value); }
    	}
    
    	public System.DateTime LastModified
    	{
            		get { return GetRelatedProperty<System.DateTime>("LastModified"); }
            		set { SetRelatedProperty("LastModified", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class BaseEntity : BrightstarEntityObject, IBaseEntity 
    {
    	public BaseEntity(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public BaseEntity(BrightstarEntityContext context) : base(context, typeof(BaseEntity)) { }
    	public BaseEntity() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity
    
    	public System.String BaseStringValue
    	{
            		get { return GetRelatedProperty<System.String>("BaseStringValue"); }
            		set { SetRelatedProperty("BaseStringValue", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class ChildKeyEntity : BrightstarEntityObject, IChildKeyEntity 
    {
    	public ChildKeyEntity(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public ChildKeyEntity(BrightstarEntityContext context) : base(context, typeof(ChildKeyEntity)) { }
    	public ChildKeyEntity() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IChildKeyEntity
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity Parent
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity>("Parent"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity>("Parent", value); }
    	}
    
    	public System.Int32 Position
    	{
            		get { return GetRelatedProperty<System.Int32>("Position"); }
            		set { SetRelatedProperty("Position", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class Company : BrightstarEntityObject, ICompany 
    {
    	public Company(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Company(BrightstarEntityContext context) : base(context, typeof(Company)) { }
    	public Company() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.ICompany
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public System.String TickerSymbol
    	{
            		get { return GetRelatedProperty<System.String>("TickerSymbol"); }
            		set { SetRelatedProperty("TickerSymbol", value); }
    	}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.IMarket ListedOn
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IMarket>("ListedOn"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IMarket>("ListedOn", value); }
    	}
    
    	public System.Decimal CurrentSharePrice
    	{
            		get { return GetRelatedProperty<System.Decimal>("CurrentSharePrice"); }
            		set { SetRelatedProperty("CurrentSharePrice", value); }
    	}
    
    	public System.Double CurrentMarketCap
    	{
            		get { return GetRelatedProperty<System.Double>("CurrentMarketCap"); }
            		set { SetRelatedProperty("CurrentMarketCap", value); }
    	}
    
    	public System.Int32 HeadCount
    	{
            		get { return GetRelatedProperty<System.Int32>("HeadCount"); }
            		set { SetRelatedProperty("HeadCount", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class CompositeKeyEntity : BrightstarEntityObject, ICompositeKeyEntity 
    {
    	public CompositeKeyEntity(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public CompositeKeyEntity(BrightstarEntityContext context) : base(context, typeof(CompositeKeyEntity)) { }
    	public CompositeKeyEntity() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.ICompositeKeyEntity
    
    	public System.String First
    	{
            		get { return GetRelatedProperty<System.String>("First"); }
            		set { SetRelatedProperty("First", value); }
    	}
    
    	public System.Int32 Second
    	{
            		get { return GetRelatedProperty<System.Int32>("Second"); }
            		set { SetRelatedProperty("Second", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class Concept : BrightstarEntityObject, IConcept 
    {
    	public Concept(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Concept(BrightstarEntityContext context) : base(context, typeof(Concept)) { }
    	public Concept() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IConcept
    	public System.Collections.Generic.ICollection<BrightstarDB.Rdf.PlainLiteral> PrefLabel
    	{
    		get { return GetRelatedLiteralPropertiesCollection<BrightstarDB.Rdf.PlainLiteral>("PrefLabel"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<BrightstarDB.Rdf.PlainLiteral>("PrefLabel", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class DBPediaPerson : BrightstarEntityObject, IDBPediaPerson 
    {
    	public DBPediaPerson(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public DBPediaPerson(BrightstarEntityContext context) : base(context, typeof(DBPediaPerson)) { }
    	public DBPediaPerson() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IDBPediaPerson
    
    	public System.DateTime BirthDate
    	{
            		get { return GetRelatedProperty<System.DateTime>("BirthDate"); }
            		set { SetRelatedProperty("BirthDate", value); }
    	}
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public System.String GivenName
    	{
            		get { return GetRelatedProperty<System.String>("GivenName"); }
            		set { SetRelatedProperty("GivenName", value); }
    	}
    
    	public System.String Surname
    	{
            		get { return GetRelatedProperty<System.String>("Surname"); }
            		set { SetRelatedProperty("Surname", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class Department : BrightstarEntityObject, IDepartment 
    {
    	public Department(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Department(BrightstarEntityContext context) : base(context, typeof(Department)) { }
    	public Department() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IDepartment
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public System.Int32 DeptId
    	{
            		get { return GetRelatedProperty<System.Int32>("DeptId"); }
            		set { SetRelatedProperty("DeptId", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson> Persons
    	{
    		get { return GetRelatedObjects<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Persons"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedObjects("Persons", value); }
    								}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class DerivedEntity : BrightstarEntityObject, IDerivedEntity 
    {
    	public DerivedEntity(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public DerivedEntity(BrightstarEntityContext context) : base(context, typeof(DerivedEntity)) { }
    	public DerivedEntity() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IDerivedEntity
    
    	public System.DateTime DateTimeProperty
    	{
            		get { return GetRelatedProperty<System.DateTime>("DateTimeProperty"); }
            		set { SetRelatedProperty("DateTimeProperty", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity> RelatedEntities
    	{
    		get { return GetRelatedObjects<BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity>("RelatedEntities"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedObjects("RelatedEntities", value); }
    								}
    	#endregion
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IBaseEntity
    
    	public System.String BaseStringValue
    	{
            		get { return GetRelatedProperty<System.String>("BaseStringValue"); }
            		set { SetRelatedProperty("BaseStringValue", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    internal partial class Entity : BrightstarEntityObject, IEntity 
    {
    	public Entity(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Entity(BrightstarEntityContext context) : base(context, typeof(Entity)) { }
    	public Entity() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IEntity
    
    	public System.String SomeString
    	{
            		get { return GetRelatedProperty<System.String>("SomeString"); }
            		set { SetRelatedProperty("SomeString", value); }
    	}
    
    	public System.DateTime SomeDateTime
    	{
            		get { return GetRelatedProperty<System.DateTime>("SomeDateTime"); }
            		set { SetRelatedProperty("SomeDateTime", value); }
    	}
    
    	public System.Nullable<System.DateTime> SomeNullableDateTime
    	{
            		get { return GetRelatedProperty<System.Nullable<System.DateTime>>("SomeNullableDateTime"); }
            		set { SetRelatedProperty("SomeNullableDateTime", value); }
    	}
    
    	public System.Boolean SomeBool
    	{
            		get { return GetRelatedProperty<System.Boolean>("SomeBool"); }
            		set { SetRelatedProperty("SomeBool", value); }
    	}
    
    	public System.Nullable<System.Boolean> NullableBool
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Boolean>>("NullableBool"); }
            		set { SetRelatedProperty("NullableBool", value); }
    	}
    
    	public System.Byte SomeByte
    	{
            		get { return GetRelatedProperty<System.Byte>("SomeByte"); }
            		set { SetRelatedProperty("SomeByte", value); }
    	}
    
    	public System.Byte AnotherByte
    	{
            		get { return GetRelatedProperty<System.Byte>("AnotherByte"); }
            		set { SetRelatedProperty("AnotherByte", value); }
    	}
    
    	public System.Nullable<System.Byte> NullableByte
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Byte>>("NullableByte"); }
            		set { SetRelatedProperty("NullableByte", value); }
    	}
    
    	public System.Nullable<System.Byte> AnotherNullableByte
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Byte>>("AnotherNullableByte"); }
            		set { SetRelatedProperty("AnotherNullableByte", value); }
    	}
    
    	public System.Char SomeChar
    	{
            		get { return GetRelatedProperty<System.Char>("SomeChar"); }
            		set { SetRelatedProperty("SomeChar", value); }
    	}
    
    	public System.Char AnotherChar
    	{
            		get { return GetRelatedProperty<System.Char>("AnotherChar"); }
            		set { SetRelatedProperty("AnotherChar", value); }
    	}
    
    	public System.Nullable<System.Char> NullableChar
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Char>>("NullableChar"); }
            		set { SetRelatedProperty("NullableChar", value); }
    	}
    
    	public System.Nullable<System.Char> AnotherNullableChar
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Char>>("AnotherNullableChar"); }
            		set { SetRelatedProperty("AnotherNullableChar", value); }
    	}
    
    	public System.Decimal SomeDecimal
    	{
            		get { return GetRelatedProperty<System.Decimal>("SomeDecimal"); }
            		set { SetRelatedProperty("SomeDecimal", value); }
    	}
    
    	public System.Double SomeDouble
    	{
            		get { return GetRelatedProperty<System.Double>("SomeDouble"); }
            		set { SetRelatedProperty("SomeDouble", value); }
    	}
    
    	public System.Single SomeFloat
    	{
            		get { return GetRelatedProperty<System.Single>("SomeFloat"); }
            		set { SetRelatedProperty("SomeFloat", value); }
    	}
    
    	public System.Int32 SomeInt
    	{
            		get { return GetRelatedProperty<System.Int32>("SomeInt"); }
            		set { SetRelatedProperty("SomeInt", value); }
    	}
    
    	public System.Nullable<System.Int32> SomeNullableInt
    	{
            		get { return GetRelatedProperty<System.Nullable<System.Int32>>("SomeNullableInt"); }
            		set { SetRelatedProperty("SomeNullableInt", value); }
    	}
    
    	public System.Int64 SomeLong
    	{
            		get { return GetRelatedProperty<System.Int64>("SomeLong"); }
            		set { SetRelatedProperty("SomeLong", value); }
    	}
    
    	public System.SByte SomeSByte
    	{
            		get { return GetRelatedProperty<System.SByte>("SomeSByte"); }
            		set { SetRelatedProperty("SomeSByte", value); }
    	}
    
    	public System.SByte AnotherSByte
    	{
            		get { return GetRelatedProperty<System.SByte>("AnotherSByte"); }
            		set { SetRelatedProperty("AnotherSByte", value); }
    	}
    
    	public System.Int16 SomeShort
    	{
            		get { return GetRelatedProperty<System.Int16>("SomeShort"); }
            		set { SetRelatedProperty("SomeShort", value); }
    	}
    
    	public System.Int16 AnotherShort
    	{
            		get { return GetRelatedProperty<System.Int16>("AnotherShort"); }
            		set { SetRelatedProperty("AnotherShort", value); }
    	}
    
    	public System.UInt32 SomeUInt
    	{
            		get { return GetRelatedProperty<System.UInt32>("SomeUInt"); }
            		set { SetRelatedProperty("SomeUInt", value); }
    	}
    
    	public System.UInt32 AnotherUInt
    	{
            		get { return GetRelatedProperty<System.UInt32>("AnotherUInt"); }
            		set { SetRelatedProperty("AnotherUInt", value); }
    	}
    
    	public System.UInt64 SomeULong
    	{
            		get { return GetRelatedProperty<System.UInt64>("SomeULong"); }
            		set { SetRelatedProperty("SomeULong", value); }
    	}
    
    	public System.UInt64 AnotherULong
    	{
            		get { return GetRelatedProperty<System.UInt64>("AnotherULong"); }
            		set { SetRelatedProperty("AnotherULong", value); }
    	}
    
    	public System.UInt16 SomeUShort
    	{
            		get { return GetRelatedProperty<System.UInt16>("SomeUShort"); }
            		set { SetRelatedProperty("SomeUShort", value); }
    	}
    
    	public System.UInt16 AnotherUShort
    	{
            		get { return GetRelatedProperty<System.UInt16>("AnotherUShort"); }
            		set { SetRelatedProperty("AnotherUShort", value); }
    	}
    
    	public System.Byte[] SomeByteArray
    	{
            		get { return GetRelatedProperty<System.Byte[]>("SomeByteArray"); }
            		set { SetRelatedProperty("SomeByteArray", value); }
    	}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.TestEnumeration SomeEnumeration
    	{
            		get { return GetRelatedProperty<BrightstarDB.Portable.Tests.EntityFramework.Model.TestEnumeration>("SomeEnumeration"); }
            		set { SetRelatedProperty("SomeEnumeration", value); }
    	}
    
    	public System.Nullable<BrightstarDB.Portable.Tests.EntityFramework.Model.TestEnumeration> SomeNullableEnumeration
    	{
            		get { return GetRelatedProperty<System.Nullable<BrightstarDB.Portable.Tests.EntityFramework.Model.TestEnumeration>>("SomeNullableEnumeration"); }
            		set { SetRelatedProperty("SomeNullableEnumeration", value); }
    	}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.TestFlagsEnumeration SomeFlagsEnumeration
    	{
            		get { return GetRelatedProperty<BrightstarDB.Portable.Tests.EntityFramework.Model.TestFlagsEnumeration>("SomeFlagsEnumeration"); }
            		set { SetRelatedProperty("SomeFlagsEnumeration", value); }
    	}
    
    	public System.Nullable<BrightstarDB.Portable.Tests.EntityFramework.Model.TestFlagsEnumeration> SomeNullableFlagsEnumeration
    	{
            		get { return GetRelatedProperty<System.Nullable<BrightstarDB.Portable.Tests.EntityFramework.Model.TestFlagsEnumeration>>("SomeNullableFlagsEnumeration"); }
            		set { SetRelatedProperty("SomeNullableFlagsEnumeration", value); }
    	}
    	public System.Collections.Generic.ICollection<System.String> CollectionOfStrings
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.String>("CollectionOfStrings"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<System.String>("CollectionOfStrings", value); }
    	}
    	public System.Collections.Generic.ICollection<System.DateTime> CollectionOfDateTimes
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.DateTime>("CollectionOfDateTimes"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<System.DateTime>("CollectionOfDateTimes", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Boolean> CollectionOfBools
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Boolean>("CollectionOfBools"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<System.Boolean>("CollectionOfBools", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Decimal> CollectionOfDecimals
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Decimal>("CollectionOfDecimals"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<System.Decimal>("CollectionOfDecimals", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Double> CollectionOfDoubles
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Double>("CollectionOfDoubles"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<System.Double>("CollectionOfDoubles", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Single> CollectionOfFloats
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Single>("CollectionOfFloats"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<System.Single>("CollectionOfFloats", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Int32> CollectionOfInts
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Int32>("CollectionOfInts"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<System.Int32>("CollectionOfInts", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Int64> CollectionOfLong
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Int64>("CollectionOfLong"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<System.Int64>("CollectionOfLong", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class FoafAgent : BrightstarEntityObject, IFoafAgent 
    {
    	public FoafAgent(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public FoafAgent(BrightstarEntityContext context) : base(context, typeof(FoafAgent)) { }
    	public FoafAgent() : base() { }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafAgent
    	public System.Collections.Generic.ICollection<System.String> MboxSums
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.String>("MboxSums"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<System.String>("MboxSums", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class FoafPerson : BrightstarEntityObject, IFoafPerson 
    {
    	public FoafPerson(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public FoafPerson(BrightstarEntityContext context) : base(context, typeof(FoafPerson)) { }
    	public FoafPerson() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafPerson
    	
    	[System.ComponentModel.DataAnnotations.DisplayAttribute(Name="Also Known As")]
    	public System.String Nickname
    	{
            		get { return GetRelatedProperty<System.String>("Nickname"); }
            		set { SetRelatedProperty("Nickname", value); }
    	}
    	
    	[System.ComponentModel.DataAnnotations.RequiredAttribute]	
    	[System.ComponentModel.DataAnnotations.CustomValidationAttribute(typeof(MyCustomValidator), "ValidateName", ErrorMessage="Custom error message")]
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public System.String Organisation
    	{
            		get { return GetRelatedProperty<System.String>("Organisation"); }
            		set { SetRelatedProperty("Organisation", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafPerson> Knows
    	{
    		get { return GetRelatedObjects<BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafPerson>("Knows"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedObjects("Knows", value); }
    								}
    	public System.Collections.Generic.ICollection<BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafPerson> KnownBy
    	{
    		get { return GetRelatedObjects<BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafPerson>("KnownBy"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedObjects("KnownBy", value); }
    								}
    	
    	[System.ComponentModel.DataAnnotations.DataTypeAttribute(DataType.Date)]
    	public System.Nullable<System.DateTime> BirthDate
    	{
            		get { return GetRelatedProperty<System.Nullable<System.DateTime>>("BirthDate"); }
            		set { SetRelatedProperty("BirthDate", value); }
    	}
    
    	public System.Uri Homepage
    	{
            		get { return GetRelatedProperty<System.Uri>("Homepage"); }
            		set { SetRelatedProperty("Homepage", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IFoafAgent
    	public System.Collections.Generic.ICollection<System.String> MboxSums
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.String>("MboxSums"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<System.String>("MboxSums", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class HierarchicalKeyEntity : BrightstarEntityObject, IHierarchicalKeyEntity 
    {
    	public HierarchicalKeyEntity(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public HierarchicalKeyEntity(BrightstarEntityContext context) : base(context, typeof(HierarchicalKeyEntity)) { }
    	public HierarchicalKeyEntity() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IHierarchicalKeyEntity
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.IHierarchicalKeyEntity Parent
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IHierarchicalKeyEntity>("Parent"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IHierarchicalKeyEntity>("Parent", value); }
    	}
    
    	public System.String Code
    	{
            		get { return GetRelatedProperty<System.String>("Code"); }
            		set { SetRelatedProperty("Code", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class IdentityClashTest : BrightstarEntityObject, IIdentityClashTest 
    {
    	public IdentityClashTest(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public IdentityClashTest(BrightstarEntityContext context) : base(context, typeof(IdentityClashTest)) { }
    	public IdentityClashTest() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTest
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class IdentityClashTestLevel1 : BrightstarEntityObject, IIdentityClashTestLevel1 
    {
    	public IdentityClashTestLevel1(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public IdentityClashTestLevel1(BrightstarEntityContext context) : base(context, typeof(IdentityClashTestLevel1)) { }
    	public IdentityClashTestLevel1() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel1
    	#endregion
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTest
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class IdentityClashTestLevel2 : BrightstarEntityObject, IIdentityClashTestLevel2 
    {
    	public IdentityClashTestLevel2(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public IdentityClashTestLevel2(BrightstarEntityContext context) : base(context, typeof(IdentityClashTestLevel2)) { }
    	public IdentityClashTestLevel2() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel2
    	#endregion
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTestLevel1
    	#endregion
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IIdentityClashTest
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class JobRole : BrightstarEntityObject, IJobRole 
    {
    	public JobRole(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public JobRole(BrightstarEntityContext context) : base(context, typeof(JobRole)) { }
    	public JobRole() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IJobRole
    
    	public System.String Description
    	{
            		get { return GetRelatedProperty<System.String>("Description"); }
            		set { SetRelatedProperty("Description", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson> Persons
    	{
    		get { return GetRelatedObjects<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Persons"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedObjects("Persons", value); }
    								}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    internal partial class LowerKeyEntity : BrightstarEntityObject, ILowerKeyEntity 
    {
    	public LowerKeyEntity(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public LowerKeyEntity(BrightstarEntityContext context) : base(context, typeof(LowerKeyEntity)) { }
    	public LowerKeyEntity() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.ILowerKeyEntity
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class Market : BrightstarEntityObject, IMarket 
    {
    	public Market(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Market(BrightstarEntityContext context) : base(context, typeof(Market)) { }
    	public Market() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IMarket
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Portable.Tests.EntityFramework.Model.ICompany> ListedCompanies
    	{
    		get { return GetRelatedObjects<BrightstarDB.Portable.Tests.EntityFramework.Model.ICompany>("ListedCompanies"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedObjects("ListedCompanies", value); }
    								}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class Person : BrightstarEntityObject, IPerson 
    {
    	public Person(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Person(BrightstarEntityContext context) : base(context, typeof(Person)) { }
    	public Person() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public System.Nullable<System.DateTime> DateOfBirth
    	{
            		get { return GetRelatedProperty<System.Nullable<System.DateTime>>("DateOfBirth"); }
            		set { SetRelatedProperty("DateOfBirth", value); }
    	}
    
    	public System.Int32 Age
    	{
            		get { return GetRelatedProperty<System.Int32>("Age"); }
            		set { SetRelatedProperty("Age", value); }
    	}
    
    	public System.Int32 Salary
    	{
            		get { return GetRelatedProperty<System.Int32>("Salary"); }
            		set { SetRelatedProperty("Salary", value); }
    	}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson Mother
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Mother"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Mother", value); }
    	}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson Father
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Father"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Father", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson> Friends
    	{
    		get { return GetRelatedObjects<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Friends"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedObjects("Friends", value); }
    								}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.IAnimal Pet
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IAnimal>("Pet"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IAnimal>("Pet", value); }
    	}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill MainSkill
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill>("MainSkill"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill>("MainSkill", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill> Skills
    	{
    		get { return GetRelatedObjects<BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill>("Skills"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedObjects("Skills", value); }
    								}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.IDepartment Department
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IDepartment>("Department"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IDepartment>("Department", value); }
    	}
    
    	public System.Int32 EmployeeId
    	{
            		get { return GetRelatedProperty<System.Int32>("EmployeeId"); }
            		set { SetRelatedProperty("EmployeeId", value); }
    	}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.IJobRole JobRole
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IJobRole>("JobRole"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IJobRole>("JobRole", value); }
    	}
    	public System.Collections.Generic.ICollection<System.Uri> Websites
    	{
    		get { return GetRelatedLiteralPropertiesCollection<System.Uri>("Websites"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedLiteralPropertiesCollection<System.Uri>("Websites", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class Session : BrightstarEntityObject, ISession 
    {
    	public Session(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Session(BrightstarEntityContext context) : base(context, typeof(Session)) { }
    	public Session() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.ISession
    
    	public System.String Speaker
    	{
            		get { return GetRelatedProperty<System.String>("Speaker"); }
            		set { SetRelatedProperty("Speaker", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class EveningSession : BrightstarEntityObject, IEveningSession 
    {
    	public EveningSession(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public EveningSession(BrightstarEntityContext context) : base(context, typeof(EveningSession)) { }
    	public EveningSession() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IEveningSession
    
    	public System.String DateTime
    	{
            		get { return GetRelatedProperty<System.String>("DateTime"); }
            		set { SetRelatedProperty("DateTime", value); }
    	}
    
    	public System.Boolean FreeBeer
    	{
            		get { return GetRelatedProperty<System.Boolean>("FreeBeer"); }
            		set { SetRelatedProperty("FreeBeer", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.ISession
    
    	public System.String Speaker
    	{
            		get { return GetRelatedProperty<System.String>("Speaker"); }
            		set { SetRelatedProperty("Speaker", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class TechnicalEveningSession : BrightstarEntityObject, ITechnicalEveningSession 
    {
    	public TechnicalEveningSession(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public TechnicalEveningSession(BrightstarEntityContext context) : base(context, typeof(TechnicalEveningSession)) { }
    	public TechnicalEveningSession() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.ITechnicalEveningSession
    
    	public System.String Subject
    	{
            		get { return GetRelatedProperty<System.String>("Subject"); }
            		set { SetRelatedProperty("Subject", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IEveningSession
    
    	public System.String DateTime
    	{
            		get { return GetRelatedProperty<System.String>("DateTime"); }
            		set { SetRelatedProperty("DateTime", value); }
    	}
    
    	public System.Boolean FreeBeer
    	{
            		get { return GetRelatedProperty<System.Boolean>("FreeBeer"); }
            		set { SetRelatedProperty("FreeBeer", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.ISession
    
    	public System.String Speaker
    	{
            		get { return GetRelatedProperty<System.String>("Speaker"); }
            		set { SetRelatedProperty("Speaker", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class Skill : BrightstarEntityObject, ISkill 
    {
    	public Skill(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Skill(BrightstarEntityContext context) : base(context, typeof(Skill)) { }
    	public Skill() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson Expert
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Expert"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("Expert", value); }
    	}
    
    	public BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill Parent
    	{
            get { return GetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill>("Parent"); }
            set { SetRelatedObject<BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill>("Parent", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill> Children
    	{
    		get { return GetRelatedObjects<BrightstarDB.Portable.Tests.EntityFramework.Model.ISkill>("Children"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedObjects("Children", value); }
    								}
    	public System.Collections.Generic.ICollection<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson> SkilledPeople
    	{
    		get { return GetRelatedObjects<BrightstarDB.Portable.Tests.EntityFramework.Model.IPerson>("SkilledPeople"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedObjects("SkilledPeople", value); }
    								}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class StringKeyEntity : BrightstarEntityObject, IStringKeyEntity 
    {
    	public StringKeyEntity(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public StringKeyEntity(BrightstarEntityContext context) : base(context, typeof(StringKeyEntity)) { }
    	public StringKeyEntity() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.IStringKeyEntity
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    
    	public System.String Description
    	{
            		get { return GetRelatedProperty<System.String>("Description"); }
            		set { SetRelatedProperty("Description", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDB.Portable.Tests.EntityFramework.Model 
{
    
    public partial class Trackable : BrightstarEntityObject, ITrackable 
    {
    	public Trackable(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Trackable(BrightstarEntityContext context) : base(context, typeof(Trackable)) { }
    	public Trackable() : base() { }
    	#region Implementation of BrightstarDB.Portable.Tests.EntityFramework.Model.ITrackable
    
    	public System.DateTime Created
    	{
            		get { return GetRelatedProperty<System.DateTime>("Created"); }
            		set { SetRelatedProperty("Created", value); }
    	}
    
    	public System.DateTime LastModified
    	{
            		get { return GetRelatedProperty<System.DateTime>("LastModified"); }
            		set { SetRelatedProperty("LastModified", value); }
    	}
    	#endregion
    }
}
