//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightstarDB.Polaris {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrightstarDB.Polaris.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polaris Management Tool for BrightstarDB.
        /// </summary>
        internal static string AboutHeading {
            get {
                return ResourceManager.GetString("AboutHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release: {0}, Build: {1}
        ///
        ///Copyright (c) 2013 Khalil Ahmed, Graham Moore.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutInfo {
            get {
                return ResourceManager.GetString("AboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application makes use of the following open-source components:
        ///
        ///dotNetRDF (http://www.dotnetrdf.org/)
        ///------------------------------------------
        ///Copyright (c) 2011 Rob Vesse
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Softwa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Acknowledgements {
            get {
                return ResourceManager.GetString("Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the store &apos;{0}&apos; from the server ?
        ///This operation cannot be undone!.
        /// </summary>
        internal static string DeleteStoreDialogContent {
            get {
                return ResourceManager.GetString("DeleteStoreDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Store ?.
        /// </summary>
        internal static string DeleteStoreDialogTitle {
            get {
                return ResourceManager.GetString("DeleteStoreDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the root folder for the Brightstar service. This folder will contain a subfolder for each store created within the service..
        /// </summary>
        internal static string DirectorySelectorDescription {
            get {
                return ResourceManager.GetString("DirectorySelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently remove the server connection &apos;{0}&apos; from the server list ?.
        /// </summary>
        internal static string DisconnectServerDialogContent {
            get {
                return ResourceManager.GetString("DisconnectServerDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Server from Server List ?.
        /// </summary>
        internal static string DisconnectServerDialogTitle {
            get {
                return ResourceManager.GetString("DisconnectServerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export of data from store &apos;{0}&apos; has completed successfully. The data can be found on the BrightstarDB server under the import directory..
        /// </summary>
        internal static string ExportCompletedDialogMsg {
            get {
                return ResourceManager.GetString("ExportCompletedDialogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Completed.
        /// </summary>
        internal static string ExportCompletedDialogTitle {
            get {
                return ResourceManager.GetString("ExportCompletedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export of data from store &apos;{0}&apos; failed. Check the export tab for details..
        /// </summary>
        internal static string ExportFailedDialogMsg {
            get {
                return ResourceManager.GetString("ExportFailedDialogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Failed.
        /// </summary>
        internal static string ExportFailedDialogTitle {
            get {
                return ResourceManager.GetString("ExportFailedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Export.
        /// </summary>
        internal static string ExportTabDefaultTitle {
            get {
                return ResourceManager.GetString("ExportTabDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error prevented the export job from running..
        /// </summary>
        internal static string ExportUnexpectedErrorMsg {
            get {
                return ResourceManager.GetString("ExportUnexpectedErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTriples (*.nt)|*.nt;*.nt.gz|NQuads (*.nq)|*.nq;*.nq.gz|RDF/XML (*.rdf)|*.rdf;*.rdf.gz|RDF/JSON (*.rj;*.json)|*.rj;*.json;*.rj.gz;*.json.gz|Notation3 (*.n3)|*.n3;*.n3.gz|Turtle (*.ttl)|*.ttl;*.ttl.gz|All Files(*.*)|*.*.
        /// </summary>
        internal static string FileSelectorOptions {
            get {
                return ResourceManager.GetString("FileSelectorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} History.
        /// </summary>
        internal static string HistoryTabDefaultTitle {
            get {
                return ResourceManager.GetString("HistoryTabDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import of data into store &apos;{0}&apos; has completed successfully..
        /// </summary>
        internal static string ImportCompletedDialogMsg {
            get {
                return ResourceManager.GetString("ImportCompletedDialogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Completed.
        /// </summary>
        internal static string ImportCompletedDialogTitle {
            get {
                return ResourceManager.GetString("ImportCompletedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import of data into store &apos;{0}&apos; failed. Check the import tab for details..
        /// </summary>
        internal static string ImportFailedDialogMsg {
            get {
                return ResourceManager.GetString("ImportFailedDialogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Failed.
        /// </summary>
        internal static string ImportFailedDialogTitle {
            get {
                return ResourceManager.GetString("ImportFailedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find import file &apos;{0}&apos;..
        /// </summary>
        internal static string ImportFileNotFound {
            get {
                return ResourceManager.GetString("ImportFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is quite large (over 50MB).
        ///
        ///A local import may require a large amount of memory on this machine as well as a fast network connection to the server.
        ///If possible consider copying the file to the BrightstarDB server&apos;s import folder and using a Remote import job instead.
        ///
        ///Are you sure you want to attempt to import this file with a Local import job ?.
        /// </summary>
        internal static string ImportFileSizeWarningMsg {
            get {
                return ResourceManager.GetString("ImportFileSizeWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size Warning.
        /// </summary>
        internal static string ImportFileSizeWarningTitle {
            get {
                return ResourceManager.GetString("ImportFileSizeWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import file is too large to be processed in memory on the client. Please copy this file to the server and use a Remote import instead..
        /// </summary>
        internal static string ImportFileTooLarge {
            get {
                return ResourceManager.GetString("ImportFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An older Polaris configuration file has been found. Do you want to import this existing configuration ? If you choose No, a new empty configuration will be created for you..
        /// </summary>
        internal static string ImportLegacyConfigurationMessage {
            get {
                return ResourceManager.GetString("ImportLegacyConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Old Configuration.
        /// </summary>
        internal static string ImportLegacyConfigurationTitle {
            get {
                return ResourceManager.GetString("ImportLegacyConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Import.
        /// </summary>
        internal static string ImportTabDefaultTitle {
            get {
                return ResourceManager.GetString("ImportTabDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error prevented the import job from running..
        /// </summary>
        internal static string ImportUnexpectedErrorMsg {
            get {
                return ResourceManager.GetString("ImportUnexpectedErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Connection specifies how Polaris should connect to a BrightstarDB store. This may be either a direct connection to the directory or (recommended) a connection to a BrightstarDB server.
        ///
        ///You currently have no connections defined. Would you like to create a new connection now ?.
        /// </summary>
        internal static string NoConnectionsMessage {
            get {
                return ResourceManager.GetString("NoConnectionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connections Defined.
        /// </summary>
        internal static string NoConnectionsTitle {
            get {
                return ResourceManager.GetString("NoConnectionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when parsing the content of the file {0}. Cause: {1}.
        /// </summary>
        internal static string ParseErrorDescription {
            get {
                return ResourceManager.GetString("ParseErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Parsing RDF File.
        /// </summary>
        internal static string ParseErrorTitle {
            get {
                return ResourceManager.GetString("ParseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Query.
        /// </summary>
        internal static string QueryTabDefaultTitle {
            get {
                return ResourceManager.GetString("QueryTabDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Statistics.
        /// </summary>
        internal static string StatisticsTabDefaultTitle {
            get {
                return ResourceManager.GetString("StatisticsTabDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create new store. {0}.
        /// </summary>
        internal static string StoreCreateFailed {
            get {
                return ResourceManager.GetString("StoreCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Creation Failed.
        /// </summary>
        internal static string StoreCreateFailedTitle {
            get {
                return ResourceManager.GetString("StoreCreateFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction failed..
        /// </summary>
        internal static string TransactionFailed {
            get {
                return ResourceManager.GetString("TransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction completed successfully..
        /// </summary>
        internal static string TransactionSuccess {
            get {
                return ResourceManager.GetString("TransactionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Transaction.
        /// </summary>
        internal static string TransactionTabDefaultTitle {
            get {
                return ResourceManager.GetString("TransactionTabDefaultTitle", resourceCulture);
            }
        }
    }
}
